package handler

import (
	"errors"
	"fmt"
	"net/http"
	"slices"
	"strings"

	"github.com/go-chi/chi/v5"

	scansvc "github.com/openctemio/openctem/api/internal/app/scan"
	"github.com/openctemio/openctem/api/internal/infra/http/middleware"
	"github.com/openctemio/openctem/api/pkg/apierror"
	"github.com/openctemio/openctem/api/pkg/domain/shared"
	"github.com/openctemio/openctem/api/pkg/logger"
	"github.com/openctemio/openctem/api/pkg/safetext"
)

// CIPlatform enumerates the platforms GenerateSnippet knows how to
// emit for. The raw string is the value the client sends via the
// ?platform= query param.
const (
	ciPlatformGitHub  = "github"
	ciPlatformGitLab  = "gitlab"
	ciPlatformJenkins = "jenkins"
)

// supportedCIPlatforms is the single source of truth for the error
// message and the validation check — keeps them from drifting.
var supportedCIPlatforms = []string{ciPlatformGitHub, ciPlatformGitLab, ciPlatformJenkins}

// CIHandler handles HTTP requests for CI/CD snippet generation.
type CIHandler struct {
	service *scansvc.Service
	logger  *logger.Logger
}

// NewCIHandler creates a new CIHandler.
func NewCIHandler(service *scansvc.Service, log *logger.Logger) *CIHandler {
	return &CIHandler{
		service: service,
		logger:  log.With("handler", "ci"),
	}
}

// GenerateSnippet handles GET /api/v1/scans/{id}/ci-snippet
// @Summary      Generate CI/CD snippet
// @Description  Generate a CI/CD pipeline snippet for a scan configuration
// @Tags         Scans
// @Produce      text/plain
// @Param        id        path      string  true   "Scan ID"
// @Param        platform  query     string  true   "CI/CD platform (github, gitlab, jenkins)"
// @Success      200  {string}  string  "YAML or pipeline snippet"
// @Failure      400  {object}  apierror.Error
// @Failure      404  {object}  apierror.Error
// @Failure      500  {object}  apierror.Error
// @Security     BearerAuth
// @Router       /scans/{id}/ci-snippet [get]
func (h *CIHandler) GenerateSnippet(w http.ResponseWriter, r *http.Request) {
	scanID := chi.URLParam(r, "id")
	tenantID := middleware.GetTenantID(r.Context())
	platform := r.URL.Query().Get("platform")

	if platform == "" {
		apierror.BadRequest(fmt.Sprintf("platform query parameter is required (%s)", strings.Join(supportedCIPlatforms, ", "))).WriteJSON(w)
		return
	}

	platform = strings.ToLower(platform)
	if !slices.Contains(supportedCIPlatforms, platform) {
		apierror.BadRequest(fmt.Sprintf("unsupported platform: must be one of %s", strings.Join(supportedCIPlatforms, ", "))).WriteJSON(w)
		return
	}

	sc, err := h.service.GetScan(r.Context(), tenantID, scanID)
	if err != nil {
		h.handleServiceError(w, err)
		return
	}

	var snippet string
	switch platform {
	case ciPlatformGitHub:
		snippet = generateGitHubActionsSnippet(sc.Name, sc.ID.String(), sc.ScannerName)
	case ciPlatformGitLab:
		snippet = generateGitLabCISnippet(sc.Name, sc.ID.String(), sc.ScannerName)
	case ciPlatformJenkins:
		snippet = generateJenkinsfileSnippet(sc.Name, sc.ID.String(), sc.ScannerName)
	}

	contentType := "text/plain; charset=utf-8"
	if platform == ciPlatformGitHub || platform == ciPlatformGitLab {
		contentType = "text/yaml; charset=utf-8"
	}

	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Content-Disposition", fmt.Sprintf("inline; filename=\"openctem-%s-%s.yml\"", platform, sc.ID.String()))
	w.WriteHeader(http.StatusOK)
	fmt.Fprint(w, snippet)
}

// handleServiceError converts service errors to API errors.
func (h *CIHandler) handleServiceError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, shared.ErrNotFound):
		apierror.NotFound("Scan").WriteJSON(w)
	case errors.Is(err, shared.ErrValidation):
		apierror.BadRequest(err.Error()).WriteJSON(w)
	default:
		h.logger.Error("service error", "error", err)
		apierror.InternalError(err).WriteJSON(w)
	}
}

// snippetName is a scan name as it may appear in a generated pipeline file:
// on one line (it sits in a comment), cleaned of control characters and
// capped. A name is chosen by any member who can edit scans; a newline in it
// would end the comment and add YAML keys or Groovy code to a file an
// administrator commits with the API key in its environment.
func snippetName(name string) string {
	return safetext.SingleLine(name, 200)
}

// generateGitHubActionsSnippet generates a GitHub Actions workflow YAML snippet.
func generateGitHubActionsSnippet(scanName, scanID, _ string) string {
	scanName = snippetName(scanName)
	return fmt.Sprintf(`# OpenCTEM Security Scan - %s
# Generated by OpenCTEM CI/CD Integration
name: OpenCTEM Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger OpenCTEM Scan
        env:
          OPENCTEM_API_URL: ${{ secrets.OPENCTEM_API_URL }}
          OPENCTEM_API_KEY: ${{ secrets.OPENCTEM_API_KEY }}
        run: |
          curl -s -X POST \
            "${OPENCTEM_API_URL}/api/v1/scans/%s/trigger" \
            -H "Authorization: Bearer ${OPENCTEM_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"context": {"ci": "github_actions", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}}' \
            -o response.json -w "%%{http_code}" | grep -q "201"

      - name: Display scan result
        if: always()
        run: |
          if [ -f response.json ]; then
            echo "Scan triggered successfully"
            cat response.json | jq .
          fi
`, scanName, scanID)
}

// generateGitLabCISnippet generates a GitLab CI YAML snippet.
func generateGitLabCISnippet(scanName, scanID, _ string) string {
	scanName = snippetName(scanName)
	return fmt.Sprintf(`# OpenCTEM Security Scan - %s
# Generated by OpenCTEM CI/CD Integration
# Add OPENCTEM_API_URL and OPENCTEM_API_KEY to CI/CD variables

stages:
  - security

openctem-scan:
  stage: security
  image: curlimages/curl:latest
  variables:
    SCAN_ID: "%s"
  script:
    - |
      RESPONSE=$(curl -s -w "\n%%{http_code}" -X POST \
        "${OPENCTEM_API_URL}/api/v1/scans/${SCAN_ID}/trigger" \
        -H "Authorization: Bearer ${OPENCTEM_API_KEY}" \
        -H "Content-Type: application/json" \
        -d "{\"context\": {\"ci\": \"gitlab_ci\", \"ref\": \"${CI_COMMIT_REF_NAME}\", \"sha\": \"${CI_COMMIT_SHA}\"}}")
      HTTP_CODE=$(echo "$RESPONSE" | tail -1)
      BODY=$(echo "$RESPONSE" | head -n -1)
      echo "$BODY"
      if [ "$HTTP_CODE" != "201" ]; then
        echo "Failed to trigger scan (HTTP ${HTTP_CODE})"
        exit 1
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  allow_failure: true
`, scanName, scanID)
}

// generateJenkinsfileSnippet generates a Jenkinsfile pipeline snippet.
func generateJenkinsfileSnippet(scanName, scanID, _ string) string {
	scanName = snippetName(scanName)
	return fmt.Sprintf(`// OpenCTEM Security Scan - %s
// Generated by OpenCTEM CI/CD Integration
// Add OPENCTEM_API_URL and OPENCTEM_API_KEY as Jenkins credentials

pipeline {
    agent any

    environment {
        OPENCTEM_API_URL = credentials('openctem-api-url')
        OPENCTEM_API_KEY = credentials('openctem-api-key')
        SCAN_ID = '%s'
    }

    stages {
        stage('Security Scan') {
            steps {
                script {
                    def response = httpRequest(
                        url: "${OPENCTEM_API_URL}/api/v1/scans/${SCAN_ID}/trigger",
                        httpMode: 'POST',
                        customHeaders: [
                            [name: 'Authorization', value: "Bearer ${OPENCTEM_API_KEY}"],
                            [name: 'Content-Type', value: 'application/json']
                        ],
                        requestBody: """{"context": {"ci": "jenkins", "branch": "${env.BRANCH_NAME}", "build": "${env.BUILD_NUMBER}"}}""",
                        validResponseCodes: '201',
                        quiet: true
                    )
                    echo "OpenCTEM scan triggered successfully"
                    echo "Response: ${response.content}"
                }
            }
        }
    }

    post {
        failure {
            echo 'OpenCTEM security scan trigger failed'
        }
    }
}
`, scanName, scanID)
}
