-- Removes the composite tenant foreign keys on asset references. The
-- single-column foreign keys to assets(id) were never touched.
ALTER TABLE assets DROP CONSTRAINT IF EXISTS fk_assets_tenant_parent;
ALTER TABLE asset_access_grants DROP CONSTRAINT IF EXISTS fk_asset_access_grants_tenant_asset;
ALTER TABLE asset_attributions DROP CONSTRAINT IF EXISTS fk_asset_attributions_tenant_asset;
ALTER TABLE asset_components DROP CONSTRAINT IF EXISTS fk_asset_components_tenant_asset;
ALTER TABLE asset_identifiers DROP CONSTRAINT IF EXISTS fk_asset_identifiers_tenant_asset;
ALTER TABLE asset_relationships DROP CONSTRAINT IF EXISTS fk_asset_relationships_tenant_source_asset;
ALTER TABLE asset_relationships DROP CONSTRAINT IF EXISTS fk_asset_relationships_tenant_target_asset;
ALTER TABLE asset_services DROP CONSTRAINT IF EXISTS fk_asset_services_tenant_asset;
ALTER TABLE asset_state_history DROP CONSTRAINT IF EXISTS fk_asset_state_history_tenant_asset;
ALTER TABLE asset_type_reclassifications DROP CONSTRAINT IF EXISTS fk_asset_type_reclassifications_tenant_asset;
ALTER TABLE business_service_assets DROP CONSTRAINT IF EXISTS fk_business_service_assets_tenant_asset;
ALTER TABLE business_unit_assets DROP CONSTRAINT IF EXISTS fk_business_unit_assets_tenant_asset;
ALTER TABLE easm_dns_check_state DROP CONSTRAINT IF EXISTS fk_easm_dns_check_state_tenant_asset;
ALTER TABLE easm_evidence DROP CONSTRAINT IF EXISTS fk_easm_evidence_tenant_asset;
ALTER TABLE exposure_events DROP CONSTRAINT IF EXISTS fk_exposure_events_tenant_asset;
ALTER TABLE exposures DROP CONSTRAINT IF EXISTS fk_exposures_tenant_asset;
ALTER TABLE finding_retests DROP CONSTRAINT IF EXISTS fk_finding_retests_tenant_asset;
ALTER TABLE findings DROP CONSTRAINT IF EXISTS fk_findings_tenant_asset;
ALTER TABLE pipeline_runs DROP CONSTRAINT IF EXISTS fk_pipeline_runs_tenant_asset;
ALTER TABLE relationship_suggestions DROP CONSTRAINT IF EXISTS fk_relationship_suggestions_tenant_source_asset;
ALTER TABLE relationship_suggestions DROP CONSTRAINT IF EXISTS fk_relationship_suggestions_tenant_target_asset;
ALTER TABLE runtime_telemetry_events DROP CONSTRAINT IF EXISTS fk_runtime_telemetry_events_tenant_endpoint_asset;
ALTER TABLE scan_coverage_state DROP CONSTRAINT IF EXISTS fk_scan_coverage_state_tenant_asset;
ALTER TABLE scan_sessions DROP CONSTRAINT IF EXISTS fk_scan_sessions_tenant_asset;
ALTER TABLE sla_policies DROP CONSTRAINT IF EXISTS fk_sla_policies_tenant_asset;
ALTER TABLE suppression_rules DROP CONSTRAINT IF EXISTS fk_suppression_rules_tenant_asset;
ALTER TABLE user_accessible_assets DROP CONSTRAINT IF EXISTS fk_user_accessible_assets_tenant_asset;
