-- Recreate the indexes dropped by 001057, as they were.

CREATE INDEX IF NOT EXISTS idx_admin_users_email ON public.admin_users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_admin_users_prefix ON public.admin_users USING btree (api_key_prefix);
CREATE INDEX IF NOT EXISTS idx_ai_triage_budgets_tenant_period ON public.ai_triage_budgets USING btree (tenant_id, period_start DESC);
CREATE INDEX IF NOT EXISTS idx_ai_triage_finding ON public.ai_triage_results USING btree (finding_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_api_keys_hash ON public.api_keys USING btree (key_hash);
CREATE INDEX IF NOT EXISTS idx_api_keys_tenant ON public.api_keys USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_approvals_finding ON public.finding_status_approvals USING btree (finding_id);
CREATE INDEX IF NOT EXISTS idx_approvals_tenant_status ON public.finding_status_approvals USING btree (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_asset_components_asset ON public.asset_components USING btree (asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_components_tenant ON public.asset_components USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_dedup_review_tenant ON public.asset_dedup_review USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_group_members_group_id ON public.asset_group_members USING btree (asset_group_id);
CREATE INDEX IF NOT EXISTS idx_asset_groups_tenant_id ON public.asset_groups USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_merge_log_tenant ON public.asset_merge_log USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_owners_group ON public.asset_owners USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_asset_rel_source ON public.asset_relationships USING btree (tenant_id, source_asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_relationships_tenant_type ON public.asset_relationships USING btree (tenant_id, relationship_type);
CREATE INDEX IF NOT EXISTS idx_asset_services_asset ON public.asset_services USING btree (asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_services_tenant ON public.asset_services USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_sources_asset ON public.asset_sources USING btree (asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_sources_primary ON public.asset_sources USING btree (asset_id) WHERE (is_primary = true);
CREATE INDEX IF NOT EXISTS idx_asset_state_history_asset ON public.asset_state_history USING btree (asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_state_history_tenant ON public.asset_state_history USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_type_categories_code ON public.asset_type_categories USING btree (code);
CREATE INDEX IF NOT EXISTS idx_asset_types_code ON public.asset_types USING btree (code);
CREATE INDEX IF NOT EXISTS idx_assets_pii ON public.assets USING btree (tenant_id) WHERE (pii_data_exposed = true);
CREATE INDEX IF NOT EXISTS idx_assets_tenant_id_pk ON public.assets USING btree (tenant_id, id);
CREATE INDEX IF NOT EXISTS idx_assets_tenant_name ON public.assets USING btree (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_assets_tenant_type ON public.assets USING btree (tenant_id, asset_type);
CREATE INDEX IF NOT EXISTS idx_assignment_rules_tenant ON public.assignment_rules USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_attack_path_nodes_path_id ON public.attack_path_nodes USING btree (attack_path_id);
CREATE INDEX IF NOT EXISTS idx_attack_simulations_tenant ON public.attack_simulations USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_business_service_assets_service ON public.business_service_assets USING btree (service_id);
CREATE INDEX IF NOT EXISTS idx_business_services_tenant ON public.business_services USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_business_units_tenant ON public.business_units USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_campaign_tickets_campaign ON public.remediation_campaign_tickets USING btree (tenant_id, campaign_id);
CREATE INDEX IF NOT EXISTS idx_capabilities_tenant ON public.capabilities USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_comment_reactions_comment_id ON public.comment_reactions USING btree (comment_id);
CREATE INDEX IF NOT EXISTS idx_compliance_assessments_tenant ON public.compliance_assessments USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_compliance_controls_framework ON public.compliance_controls USING btree (framework_id);
CREATE INDEX IF NOT EXISTS idx_compliance_finding_mappings_tenant ON public.compliance_finding_mappings USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_component_licenses_component ON public.component_licenses USING btree (component_id);
CREATE INDEX IF NOT EXISTS idx_components_purl ON public.components USING btree (purl);
CREATE INDEX IF NOT EXISTS idx_control_tests_tenant ON public.control_tests USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_credentials_tenant ON public.credentials USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_data_flows_finding ON public.finding_data_flows USING btree (finding_id);
CREATE INDEX IF NOT EXISTS idx_exposure_events_tenant ON public.exposure_events USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_exposures_tenant_id ON public.exposures USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_fbo_finding ON public.finding_branch_occurrences USING btree (finding_id);
CREATE INDEX IF NOT EXISTS idx_fga_finding ON public.finding_group_assignments USING btree (finding_id);
CREATE INDEX IF NOT EXISTS idx_finding_activities_tenant ON public.finding_activities USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_finding_activities_tenant_id ON public.finding_activities USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_finding_source_categories_code ON public.finding_source_categories USING btree (code);
CREATE INDEX IF NOT EXISTS idx_finding_sources_code ON public.finding_sources USING btree (code);
CREATE INDEX IF NOT EXISTS idx_finding_suppressions_finding ON public.finding_suppressions USING btree (finding_id);
CREATE INDEX IF NOT EXISTS idx_findings_tenant_asset ON public.findings USING btree (tenant_id, asset_id);
CREATE INDEX IF NOT EXISTS idx_flow_locations_file ON public.finding_flow_locations USING btree (file_path) WHERE (file_path IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_group_members_user ON public.group_members USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_groups_tenant ON public.groups USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_integrations_tenant_id ON public.integrations USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_licenses_spdx ON public.licenses USING btree (spdx_id);
CREATE INDEX IF NOT EXISTS idx_modules_parent_module_id ON public.modules USING btree (parent_module_id) WHERE (parent_module_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_modules_slug ON public.modules USING btree (slug);
CREATE INDEX IF NOT EXISTS idx_pentest_campaigns_tenant ON public.pentest_campaigns USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_pentest_findings_tenant ON public.pentest_findings USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_status ON public.pipeline_runs USING btree (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_pipeline_steps_pipeline ON public.pipeline_steps USING btree (pipeline_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_templates_tenant ON public.pipeline_templates USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token_hash ON public.refresh_tokens USING btree (token_hash);
CREATE INDEX IF NOT EXISTS idx_remediation_campaigns_tenant ON public.remediation_campaigns USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_report_schedules_tenant ON public.report_schedules USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_repository_branches_repository_id ON public.repository_branches USING btree (repository_id);
CREATE INDEX IF NOT EXISTS idx_risk_snapshots_range ON public.risk_snapshots USING btree (tenant_id, snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON public.role_permissions USING btree (role_id);
CREATE INDEX IF NOT EXISTS idx_roles_tenant ON public.roles USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scan_profiles_tenant_id ON public.scan_profiles USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scan_sessions_tenant ON public.scan_sessions USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scanner_templates_tenant ON public.scanner_templates USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scans_tenant ON public.scans USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scans_tenant_status ON public.scans USING btree (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_scim_groups_tenant ON public.scim_groups USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scope_exclusions_tenant ON public.scope_exclusions USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scope_rules_group ON public.group_asset_scope_rules USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_scope_rules_group_tenant_active ON public.group_asset_scope_rules USING btree (group_id, tenant_id, is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_scope_rules_tenant ON public.group_asset_scope_rules USING btree (tenant_id) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_scope_targets_tenant ON public.scope_targets USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scope_targets_type ON public.scope_targets USING btree (tenant_id, target_type);
CREATE INDEX IF NOT EXISTS idx_sensors_tenant_id ON public.sensors USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_sensors_tenant_id_pk ON public.sensors USING btree (tenant_id, id);
CREATE INDEX IF NOT EXISTS idx_settings_tenant ON public.settings USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_simulation_runs_tenant ON public.attack_simulation_runs USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_step_runs_pipeline_run ON public.step_runs USING btree (pipeline_run_id);
CREATE INDEX IF NOT EXISTS idx_suppression_rules_tenant ON public.suppression_rules USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_template_sources_tenant ON public.template_sources USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_invitations_token ON public.tenant_invitations USING btree (token);
CREATE INDEX IF NOT EXISTS idx_tenant_members_tenant_id ON public.tenant_members USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_members_user_id ON public.tenant_members USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_tenant_modules_tenant ON public.tenant_modules USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_tool_configs_tenant ON public.tenant_tool_configs USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenants_slug ON public.tenants USING btree (slug);
CREATE INDEX IF NOT EXISTS idx_threat_actors_tenant ON public.threat_actors USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_threat_intel_sync_source ON public.threat_intel_sync_status USING btree (source_name);
CREATE INDEX IF NOT EXISTS idx_threat_models_tenant ON public.threat_models USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tip_tenant_id ON public.tenant_identity_providers USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tool_executions_tenant ON public.tool_executions USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tools_tenant ON public.tools USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_accessible_assets_user ON public.user_accessible_assets USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_dashboards_tenant_user ON public.user_dashboards USING btree (tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_tenant ON public.user_roles USING btree (user_id, tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_verification_checklist_finding ON public.finding_verification_checklists USING btree (finding_id);
CREATE INDEX IF NOT EXISTS idx_vulnerabilities_cve_id ON public.vulnerabilities USING btree (cve_id);
CREATE INDEX IF NOT EXISTS idx_webhooks_tenant ON public.webhooks USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_workflow_edges_workflow ON public.workflow_edges USING btree (workflow_id);
CREATE INDEX IF NOT EXISTS idx_workflow_node_runs_run ON public.workflow_node_runs USING btree (workflow_run_id);
CREATE INDEX IF NOT EXISTS idx_workflow_nodes_workflow ON public.workflow_nodes USING btree (workflow_id);
CREATE INDEX IF NOT EXISTS idx_workflows_tenant ON public.workflows USING btree (tenant_id);
