-- Module registry (RFC-064): the modules rows as configs/modules.yaml declares them.
-- Written by cmd/gen-modules (make modules-sql); CI checks the block against the
-- registry (make modules-check). A later registry change adds a new migration
-- with a new block. Idempotent.

-- BEGIN module-registry
-- Generated by cmd/gen-modules from configs/modules.yaml. Do not edit by hand.
INSERT INTO modules (id, slug, name, description, icon, category, display_order, is_active, is_core, release_status, parent_module_id)
VALUES
    ('dashboard', 'dashboard', 'Dashboard', 'Main dashboard with security overview and statistics', 'LayoutDashboard', 'core', 1, TRUE, true, 'released', NULL),
    ('assets', 'assets', 'Assets', 'The asset inventory, asset groups and every asset type', 'Server', 'core', 2, TRUE, true, 'released', NULL),
    ('findings', 'findings', 'Findings', 'Findings, approvals and exceptions, with SLA deadlines and priority classes', 'AlertTriangle', 'core', 3, TRUE, true, 'released', NULL),
    ('scans', 'scans', 'Scans', 'Scans, Scanning settings (Sensors, Profiles, Tools, Capabilities, Templates, Sources, Secret Store)', 'Search', 'core', 4, TRUE, true, 'released', NULL),
    ('attack_surface', 'attack-surface', 'Attack Surface', 'External attack surface overview — what an adversary sees before touching the network', 'Target', 'scoping', 5, TRUE, false, 'released', NULL),
    ('scope_config', 'scope-config', 'Scope Config', 'CTEM scope — which assets are in scope for prioritisation and reporting', 'Sliders', 'scoping', 6, TRUE, false, 'released', NULL),
    ('business_services', 'business-services', 'Business Services', 'Map business services to the underlying assets that power them', 'Building', 'scoping', 7, TRUE, false, 'released', NULL),
    ('ctem_cycles', 'ctem-cycles', 'CTEM Cycles', 'Gartner CTEM lifecycle — scoping, discovery, prioritisation, validation, mobilisation', 'RotateCcw', 'scoping', 8, TRUE, false, 'released', NULL),
    ('attacker_profiles', 'attacker-profiles', 'Attacker Profiles', 'Threat actor profiles used to drive attack simulation + prioritisation scoring', 'Swords', 'scoping', 9, TRUE, false, 'released', NULL),
    ('credentials', 'credentials', 'Credentials', 'Leaked credentials monitoring and detection', 'Key', 'discovery', 10, TRUE, false, 'released', NULL),
    ('relationships', 'relationships', 'Relationships', 'Asset-to-asset relationships for attack-path modelling', 'Link', 'scoping', 10, TRUE, false, 'released', NULL),
    ('scanner_templates', 'scanner-templates', 'Scanner Templates', 'Catalogue of Nuclei / Betterleaks / Semgrep templates', 'FileCode', 'settings', 10, TRUE, false, 'released', NULL),
    ('business_units', 'business-units', 'Business Units', 'Organisational units that group assets for ownership, criticality and reporting', 'Building2', 'scoping', 11, TRUE, false, 'released', NULL),
    ('components', 'components', 'Components', 'Software Components (SBOM), Ecosystems, Licenses, and vulnerability tracking', 'Package', 'discovery', 11, TRUE, false, 'released', NULL),
    ('template_sources', 'template-sources', 'Template Sources', 'Upstream git sources that templates are synced from', 'Database', 'settings', 11, TRUE, false, 'released', NULL),
    ('branches', 'branches', 'Branches', 'Code branches', 'GitBranch', 'discovery', 12, TRUE, false, 'released', NULL),
    ('crown_jewels', 'crown-jewels', 'Crown Jewels', 'Business-critical assets flagged for heightened prioritisation and monitoring', 'Crown', 'scoping', 12, TRUE, false, 'released', NULL),
    ('scan_workflows', 'scan-workflows', 'Scan Workflows', 'Scan workflows: the steps a scan runs, chained by what each step finds', 'GitBranch', 'settings', 12, TRUE, false, 'released', NULL),
    ('threat_model', 'threat-model', 'Threat Model', 'Continuous threat modelling derived from the asset graph and findings', 'Crosshair', 'scoping', 13, TRUE, false, 'released', NULL),
    ('threat_intel', 'threat_intel', 'Threat Intel', 'Threat actors and the threat intelligence workspace', 'Radar', 'prioritization', 20, TRUE, false, 'released', NULL),
    ('exposures', 'exposures', 'Exposures', 'Exposure management and non-CVE security issues', 'ShieldAlert', 'prioritization', 21, TRUE, false, 'released', NULL),
    ('ai_triage', 'ai_triage', 'AI Triage', 'AI-powered vulnerability triage (Bulk, Auto, Workflow, BYOK, Agent modes)', 'Brain', 'prioritization', 22, TRUE, false, 'released', NULL),
    ('ai_triage.bulk', 'ai_triage_bulk', 'Bulk Triage', 'Bulk triage operations', 'Layers', 'prioritization', 1, TRUE, false, 'released', 'ai_triage'),
    ('ai_triage.auto', 'ai_triage_auto', 'Auto Triage', 'Auto-triage on finding creation', 'Zap', 'prioritization', 2, TRUE, false, 'released', 'ai_triage'),
    ('ai_triage.workflow', 'ai_triage_workflow', 'Workflow Triage', 'Workflow triggers and actions', 'GitPullRequest', 'prioritization', 3, TRUE, false, 'released', 'ai_triage'),
    ('ai_triage.byok', 'ai_triage_byok', 'BYOK Mode', 'Bring Your Own Key mode', 'Key', 'prioritization', 4, TRUE, false, 'released', 'ai_triage'),
    ('ai_triage.agent', 'ai_triage_agent', 'Agent Mode', 'Self-hosted Agent mode', 'Cpu', 'prioritization', 5, TRUE, false, 'released', 'ai_triage'),
    ('ai_triage.custom_prompts', 'ai_triage_custom_prompts', 'Custom Prompts', 'Custom prompt templates', 'FileText', 'prioritization', 6, TRUE, false, 'released', 'ai_triage'),
    ('sla', 'sla', 'SLA Management', 'SLA policies for remediation time tracking', 'Clock', 'prioritization', 23, TRUE, true, 'released', NULL),
    ('priority_rules', 'priority-rules', 'Priority Rules', 'Declarative priority classification rules (P0..P3)', 'Sliders', 'prioritization', 24, TRUE, false, 'released', NULL),
    ('risk_analysis', 'risk-analysis', 'Risk Analysis', 'Aggregate risk dashboards across assets + findings', 'BarChart', 'prioritization', 25, TRUE, false, 'released', NULL),
    ('business_impact', 'business-impact', 'Business Impact', 'Business impact scoring weighted by business-services mapping', 'Building', 'prioritization', 26, TRUE, false, 'released', NULL),
    ('risk_scoring', 'risk-scoring', 'Risk Scoring', 'Risk scoring config — CVSS / EPSS / KEV / custom weights', 'TrendingUp', 'prioritization', 27, TRUE, false, 'released', NULL),
    ('pentest', 'pentest', 'Penetration Testing', 'Penetration testing campaigns, findings, retests and reports', 'Crosshair', 'validation', 30, TRUE, false, 'released', NULL),
    ('attack_simulation', 'attack-simulation', 'Attack Simulation', 'Breach & Attack Simulation (BAS) — automated adversary emulation to test security controls effectiveness', 'Swords', 'validation', 31, TRUE, false, 'beta', NULL),
    ('control_testing', 'control-testing', 'Control Testing', 'Validate security controls (firewalls, WAF, IDS/IPS) with automated test cases', 'ShieldCheck', 'validation', 32, TRUE, false, 'beta', NULL),
    ('compensating_controls', 'compensating-controls', 'Compensating Controls', 'Controls that reduce finding severity (WAF, EDR, IPS, …)', 'ShieldCheck', 'validation', 33, TRUE, false, 'released', NULL),
    ('remediation', 'remediation', 'Remediation', 'Remediation campaigns that group the fixes for many findings', 'CheckSquare', 'mobilization', 40, TRUE, false, 'released', NULL),
    ('suppressions', 'suppressions', 'Suppressions', 'Finding suppression rules to mute known false positives', 'EyeOff', 'mobilization', 41, TRUE, false, 'released', NULL),
    ('workflows', 'workflows', 'Workflows', 'Trigger-action automation for finding lifecycle (assignment, notification, sync)', 'GitPullRequest', 'mobilization', 43, TRUE, false, 'released', NULL),
    ('reports', 'reports', 'Reports', 'Security reports and analytics', 'FileText', 'insights', 50, TRUE, false, 'released', NULL),
    ('audit', 'audit', 'Audit', 'Audit log for tracking all actions', 'History', 'insights', 51, TRUE, true, 'released', NULL),
    ('ctem_maturity', 'ctem-maturity', 'CTEM Maturity', 'Per-tenant CTEM invariant health — F1-F4, B1-B7, O1-O3', 'ShieldCheck', 'insights', 52, TRUE, false, 'released', NULL),
    ('executive_summary', 'executive-summary', 'Executive Summary', 'Board-ready PDF rollup of risk, breaches, SLAs', 'FileText', 'insights', 53, TRUE, false, 'released', NULL),
    ('mitre_coverage', 'mitre-coverage', 'MITRE Coverage', 'MITRE ATT&CK technique coverage across detections + controls', 'Shield', 'insights', 54, TRUE, false, 'released', NULL),
    ('sbom_export', 'sbom-export', 'SBOM Export', 'Export Software Bill of Materials in CycloneDX / SPDX', 'Download', 'insights', 55, TRUE, false, 'released', NULL),
    ('integrations', 'integrations', 'Integrations', 'Integrations (SCM, Notifications, CI/CD, Ticketing, SIEM)', 'Plug', 'settings', 60, TRUE, true, 'released', NULL),
    ('integrations.scm', 'scm', 'SCM Integrations', 'Source code management integrations', 'GitBranch', 'settings', 1, TRUE, false, 'released', 'integrations'),
    ('integrations.notifications', 'notifications', 'Notification Channels', 'Notification channel integrations', 'Bell', 'settings', 2, TRUE, true, 'released', 'integrations'),
    ('integrations.ticketing', 'ticketing', 'Ticketing', 'Issue tracking integrations', 'Ticket', 'settings', 3, TRUE, false, 'released', 'integrations'),
    ('integrations.cloud', 'cloud', 'Cloud Providers', 'Cloud provider integrations', 'Cloud', 'settings', 4, TRUE, false, 'released', 'integrations'),
    ('integrations.siem', 'siem', 'SIEM', 'SIEM integrations', 'Shield', 'settings', 5, TRUE, false, 'released', 'integrations'),
    ('integrations.scanners', 'scanners', 'Scanners', 'External scanner integrations', 'Search', 'settings', 6, TRUE, false, 'released', 'integrations'),
    ('integrations.api', 'api_int', 'API Integrations', 'API integrations', 'Zap', 'settings', 8, TRUE, false, 'released', 'integrations'),
    ('integrations.pipelines', 'pipelines_int', 'Pipeline Integrations', 'CI/CD pipeline integrations', 'GitPullRequest', 'settings', 9, TRUE, false, 'released', 'integrations'),
    ('sensors', 'sensors', 'Sensors', 'Sensors: scanners, agents and collectors that report to the platform', 'Cpu', 'settings', 61, TRUE, true, 'released', NULL),
    ('team', 'team', 'Team', 'Team members management and invitations', 'Users', 'settings', 62, TRUE, true, 'released', NULL),
    ('groups', 'groups', 'Groups', 'Data scope groups (Teams) for access control', 'UsersCog', 'settings', 63, TRUE, true, 'released', NULL),
    ('roles', 'roles', 'Roles', 'Custom RBAC roles and permission management', 'Shield', 'settings', 64, TRUE, true, 'released', NULL),
    ('settings', 'settings', 'Settings', 'General workspace settings, Risk Scoring, and Module configuration', 'Settings', 'settings', 65, TRUE, true, 'released', NULL),
    ('api_keys', 'api_keys', 'API Keys', 'API key management for programmatic access', 'Key', 'settings', 66, TRUE, true, 'released', NULL),
    ('notification_settings', 'notification_settings', 'Notifications', 'Notification channel settings and delivery configuration', 'Bell', 'settings', 68, TRUE, true, 'released', NULL),
    ('tools', 'tools', 'Tools', 'Security tools and capabilities management', 'Wrench', 'operations', 81, TRUE, false, 'released', NULL),
    ('scan_profiles', 'scan_profiles', 'Scan Profiles', 'Scan configuration profiles', 'Sliders', 'operations', 83, TRUE, false, 'released', NULL),
    ('iocs', 'iocs', 'IOCs', 'Indicators of Compromise', 'Fingerprint', 'operations', 84, TRUE, false, 'released', NULL),
    ('compliance', 'compliance', 'Compliance', 'Compliance frameworks, controls and audit-readiness mappings', 'ClipboardCheck', 'compliance', 90, TRUE, false, 'released', NULL)
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug, name = EXCLUDED.name, description = EXCLUDED.description,
    icon = EXCLUDED.icon, category = EXCLUDED.category, display_order = EXCLUDED.display_order,
    is_active = TRUE, is_core = EXCLUDED.is_core, release_status = EXCLUDED.release_status,
    parent_module_id = EXCLUDED.parent_module_id, updated_at = NOW();
-- A row the registry no longer declares is retired: inactive, so no tenant can reach it.
UPDATE modules SET is_active = FALSE, updated_at = NOW()
 WHERE is_active AND id NOT IN ('dashboard', 'assets', 'findings', 'scans', 'attack_surface', 'scope_config', 'business_services', 'ctem_cycles', 'attacker_profiles', 'credentials', 'relationships', 'scanner_templates', 'business_units', 'components', 'template_sources', 'branches', 'crown_jewels', 'scan_workflows', 'threat_model', 'threat_intel', 'exposures', 'ai_triage', 'ai_triage.bulk', 'ai_triage.auto', 'ai_triage.workflow', 'ai_triage.byok', 'ai_triage.agent', 'ai_triage.custom_prompts', 'sla', 'priority_rules', 'risk_analysis', 'business_impact', 'risk_scoring', 'pentest', 'attack_simulation', 'control_testing', 'compensating_controls', 'remediation', 'suppressions', 'workflows', 'reports', 'audit', 'ctem_maturity', 'executive_summary', 'mitre_coverage', 'sbom_export', 'integrations', 'integrations.scm', 'integrations.notifications', 'integrations.ticketing', 'integrations.cloud', 'integrations.siem', 'integrations.scanners', 'integrations.api', 'integrations.pipelines', 'sensors', 'team', 'groups', 'roles', 'settings', 'api_keys', 'notification_settings', 'tools', 'scan_profiles', 'iocs', 'compliance');
-- END module-registry
