#!/usr/bin/env bash
#
# generate-api-types.sh — derive src/lib/api/generated/api.types.ts from the
# API's OpenAPI spec.
#
# WHY: every cross-repo bug found recently was a contract bug. The UI hand-wrote
# its API response shapes, so a field the server renamed, an endpoint that never
# existed, and a list the server exposed but the UI never asked for all looked
# identical to correct code. The event-type picker fetched
# GET /api/v1/me/event-types — a path the OSS server had never implemented —
# because someone typed the interface from a stale spec.
#
# So the shapes are generated now, from the same file the server generates from.
# Neither the spec nor this file is committed: `make generate` at the repository
# root produces both (CI and image builds run it first).
#
# Pipeline:
#   ../api/api/openapi/swagger.yaml    (generated by `make -C api swagger`; Swagger 2.0)
#     -> swagger2openapi                (2.0 has no discriminated schemas / nullable)
#     -> openapi-typescript             -> src/lib/api/generated/api.types.ts
#
# Usage:
#   scripts/generate-api-types.sh
#   OPENAPI_SPEC=/path/to/swagger.yaml scripts/generate-api-types.sh
#
# Exit codes: 0 = ok, 2 = tooling error or missing spec.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPEC="${OPENAPI_SPEC:-$REPO_ROOT/../api/api/openapi/swagger.yaml}"
OUT_REL="src/lib/api/generated/api.types.ts"
OUT="$REPO_ROOT/$OUT_REL"

if [ ! -f "$SPEC" ]; then
  echo "generate-api-types: no API spec at $SPEC" >&2
  echo "  It is generated, not committed: run \`make generate\` at the repository root" >&2
  echo "  (needs Go and Node), or \`make generate-docker\` (needs only Docker)." >&2
  exit 2
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

# --- 1. Swagger 2.0 -> OpenAPI 3.0 ------------------------------------------
# The API generates with swaggo/swag v1, which only emits Swagger 2.0.
# openapi-typescript v7 reads 3.x only, so convert first.
if ! npx --no-install swagger2openapi \
      --yaml --outfile "$tmpdir/openapi.yaml" "$SPEC" >"$tmpdir/convert.log" 2>&1; then
  echo "generate-api-types: swagger2openapi failed:" >&2
  cat "$tmpdir/convert.log" >&2
  exit 2
fi

# --- 2. OpenAPI 3.0 -> TypeScript -------------------------------------------
if ! npx --no-install openapi-typescript "$tmpdir/openapi.yaml" \
      --output "$tmpdir/api.types.ts" >"$tmpdir/gen.log" 2>&1; then
  echo "generate-api-types: openapi-typescript failed:" >&2
  cat "$tmpdir/gen.log" >&2
  exit 2
fi

# --- 3. Header + formatting --------------------------------------------------
{
  cat <<'EOF'
/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Derived from api/api/openapi/swagger.yaml (generated from the Go handler
 * annotations and gated by api/scripts/check-openapi.sh). Not committed.
 *
 * Regenerate:  make generate   (repository root; or npm run generate:api-types
 *                               when only the spec changed)
 *
 * Prefer the named aliases in src/lib/api/generated/index.ts over reaching into
 * `components['schemas'][...]` directly — the schema keys are Go package paths
 * and will change if a handler type moves.
 */

EOF
  cat "$tmpdir/api.types.ts"
} >"$tmpdir/api.types.headed.ts"

# --config is required: the scratch file lives outside the repo, so prettier
# would not find .prettierrc and would format with its defaults.
if ! npx --no-install prettier --write "$tmpdir/api.types.headed.ts" \
      --config "$REPO_ROOT/.prettierrc" --parser typescript >"$tmpdir/fmt.log" 2>&1; then
  echo "generate-api-types: prettier failed:" >&2
  cat "$tmpdir/fmt.log" >&2
  exit 2
fi

# --- 4. Write ----------------------------------------------------------------
mkdir -p "$(dirname "$OUT")"
cp "$tmpdir/api.types.headed.ts" "$OUT"
echo "generate-api-types: wrote $OUT_REL"
