// Code generated by api/cmd/gen-relationships. DO NOT EDIT.
//
// Source of truth: api/configs/relationship-types.yaml
// Run `make generate-relationships` to regenerate.

package asset

// =============================================================================
// Relationship Type Constants
// =============================================================================
//
// These constants are generated from configs/relationship-types.yaml.
// Add a new type by editing the YAML and running the codegen — never
// add constants here by hand.
const (
	RelTypeRunsOn          RelationshipType = "runs_on"
	RelTypeDeployedTo      RelationshipType = "deployed_to"
	RelTypeContains        RelationshipType = "contains"
	RelTypeExposes         RelationshipType = "exposes"
	RelTypeResolvesTo      RelationshipType = "resolves_to"
	RelTypeCnameOf         RelationshipType = "cname_of"
	RelTypeDependsOn       RelationshipType = "depends_on"
	RelTypePeerOf          RelationshipType = "peer_of"
	RelTypeReplicatesTo    RelationshipType = "replicates_to"
	RelTypeSendsDataTo     RelationshipType = "sends_data_to"
	RelTypeStoresDataIn    RelationshipType = "stores_data_in"
	RelTypeAuthenticatesTo RelationshipType = "authenticates_to"
	RelTypeGrantedTo       RelationshipType = "granted_to"
	RelTypeHasAccessTo     RelationshipType = "has_access_to"
	RelTypeLoadBalances    RelationshipType = "load_balances"
	RelTypeProtectedBy     RelationshipType = "protected_by"
	RelTypeMonitors        RelationshipType = "monitors"
	RelTypeManages         RelationshipType = "manages"
)

// allRelationshipTypesGenerated is the canonical list of every valid
// relationship type, in the order they appear in the YAML.
var allRelationshipTypesGenerated = []RelationshipType{
	RelTypeRunsOn,
	RelTypeDeployedTo,
	RelTypeContains,
	RelTypeExposes,
	RelTypeResolvesTo,
	RelTypeCnameOf,
	RelTypeDependsOn,
	RelTypePeerOf,
	RelTypeReplicatesTo,
	RelTypeSendsDataTo,
	RelTypeStoresDataIn,
	RelTypeAuthenticatesTo,
	RelTypeGrantedTo,
	RelTypeHasAccessTo,
	RelTypeLoadBalances,
	RelTypeProtectedBy,
	RelTypeMonitors,
	RelTypeManages,
}

// RelationshipTypeMetadata holds the human-readable labels and the
// constraint table for a single relationship type.
type RelationshipTypeMetadata struct {
	ID          RelationshipType
	Category    string
	Direct      string
	Inverse     string
	Description string
	Constraints []RelationshipConstraint
}

// RelationshipConstraint defines one valid (sources, targets) combination
// for a relationship type. The full set of valid pairs for a type is the
// union of all its constraints.
type RelationshipConstraint struct {
	Sources []string
	Targets []string
}

// RelationshipTypeRegistry maps each relationship type to its metadata.
// Generated from the YAML — do not modify by hand.
var RelationshipTypeRegistry = map[RelationshipType]RelationshipTypeMetadata{
	RelTypeRunsOn: {
		ID:          RelTypeRunsOn,
		Category:    "attack_surface_mapping",
		Direct:      "Runs On",
		Inverse:     "Runs",
		Description: "Runtime location of a workload — service/container/website is currently executing on this compute. Use this for \"where it lives now\". For build/deploy events use Deployed To.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"service", "api", "website"},
				Targets: []string{"host", "endpoint", "container", "k8s_workload", "cloud_account"},
			},
			{
				Sources: []string{"database"},
				Targets: []string{"host", "container", "cloud_account"},
			},
			{
				Sources: []string{"k8s_workload"},
				Targets: []string{"k8s_cluster"},
			},
			{
				Sources: []string{"container"},
				Targets: []string{"host", "k8s_workload"},
			},
		},
	},
	RelTypeDeployedTo: {
		ID:          RelTypeDeployedTo,
		Category:    "attack_surface_mapping",
		Direct:      "Deployed To",
		Inverse:     "Has Deployment",
		Description: "Build artifact placed at a target — strictly for repos / container images / build outputs. Do NOT use this for runtime workloads (those use Runs On).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"repository", "container_image"},
				Targets: []string{"k8s_cluster", "k8s_workload", "cloud_account", "host"},
			},
		},
	},
	RelTypeContains: {
		ID:          RelTypeContains,
		Category:    "attack_surface_mapping",
		Direct:      "Contains",
		Inverse:     "Contained By",
		Description: "Hierarchical parent-child relationship. The single direction we use for ALL hierarchical edges (cluster→workload, host→container, cloud_account→host, etc). Always source = parent, target = child. Do NOT model the inverse as a separate edge.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"cloud_account"},
				Targets: []string{"host", "database", "k8s_cluster", "network", "storage", "serverless", "load_balancer"},
			},
			{
				Sources: []string{"network"},
				Targets: []string{"host", "cloud_account", "load_balancer"},
			},
			{
				Sources: []string{"host", "endpoint"},
				Targets: []string{"container", "service", "database"},
			},
			{
				Sources: []string{"k8s_cluster"},
				Targets: []string{"k8s_workload", "kubernetes_namespace"},
			},
			{
				Sources: []string{"k8s_workload"},
				Targets: []string{"container"},
			},
			{
				Sources: []string{"api_collection", "api"},
				Targets: []string{"api_endpoint"},
			},
			{
				Sources: []string{"repository"},
				Targets: []string{"container_image"},
			},
			{
				Sources: []string{"domain"},
				Targets: []string{"subdomain"},
			},
		},
	},
	RelTypeExposes: {
		ID:          RelTypeExposes,
		Category:    "attack_surface_mapping",
		Direct:      "Exposes",
		Inverse:     "Exposed By",
		Description: "Asset exposes an access surface (api/service → port/endpoint/public interface).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"host", "endpoint", "ip_address", "k8s_workload", "container"},
				Targets: []string{"api_endpoint", "service", "api"},
			},
			{
				Sources: []string{"domain"},
				Targets: []string{"website", "api", "service"},
			},
			{
				Sources: []string{"load_balancer"},
				Targets: []string{"api", "service", "website"},
			},
		},
	},
	RelTypeResolvesTo: {
		ID:          RelTypeResolvesTo,
		Category:    "attack_surface_mapping",
		Direct:      "Resolves To",
		Inverse:     "Resolved By",
		Description: "Literal DNS A/AAAA resolution — a domain or subdomain resolves to an IP record or a load balancer that owns that IP. STRICT semantic: target MUST be the network endpoint, not the server that happens to own the IP. For \"this domain leads to this server / website\" use Exposes. For subdomain → parent domain hierarchy use Contains.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"domain", "subdomain"},
				Targets: []string{"ip_address", "load_balancer"},
			},
		},
	},
	RelTypeCnameOf: {
		ID:          RelTypeCnameOf,
		Category:    "attack_surface_mapping",
		Direct:      "CNAME Of",
		Inverse:     "Has CNAME",
		Description: "DNS CNAME aliasing — this name is a CNAME record pointing to another name. Strictly for actual DNS CNAME records, NOT for subdomain hierarchy (use Contains for that). Distinct from Resolves To which captures the final A/AAAA IP record.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"domain", "subdomain"},
				Targets: []string{"domain", "subdomain"},
			},
		},
	},
	RelTypeDependsOn: {
		ID:          RelTypeDependsOn,
		Category:    "attack_path_analysis",
		Direct:      "Depends On",
		Inverse:     "Used By",
		Description: "A needs B to function (service → database; web_app → api). Use for hard runtime dependencies, NOT for peer relationships (use Peer Of) or replication (use Replicates To).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"service", "api", "website"},
				Targets: []string{"database", "api", "service", "credential"},
			},
			{
				Sources: []string{"k8s_workload"},
				Targets: []string{"container_image", "database", "api", "service"},
			},
			{
				Sources: []string{"mobile"},
				Targets: []string{"api", "service"},
			},
		},
	},
	RelTypePeerOf: {
		ID:          RelTypePeerOf,
		Category:    "attack_path_analysis",
		Direct:      "Peer Of",
		Inverse:     "Peer Of",
		Description: "Symmetric relationship between equal-rank assets — sibling services in a cluster, HA pairs, leader/follower nodes. Pick EITHER asset as source; the inverse direction is implied. Do NOT model the same pair twice.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"service", "api"},
				Targets: []string{"service", "api"},
			},
			{
				Sources: []string{"database"},
				Targets: []string{"database"},
			},
			{
				Sources: []string{"host", "endpoint", "container"},
				Targets: []string{"host", "endpoint", "container"},
			},
		},
	},
	RelTypeReplicatesTo: {
		ID:          RelTypeReplicatesTo,
		Category:    "attack_path_analysis",
		Direct:      "Replicates To",
		Inverse:     "Replicates From",
		Description: "Data replication relationship — primary database streams to replica, log shipper writes to remote, etc. Different from Sends Data To which is application-level data flow; replication is infrastructure-level state copy.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"database", "storage"},
				Targets: []string{"database", "storage"},
			},
		},
	},
	RelTypeSendsDataTo: {
		ID:          RelTypeSendsDataTo,
		Category:    "attack_path_analysis",
		Direct:      "Sends Data To",
		Inverse:     "Receives Data From",
		Description: "Application data flow in-transit (service → service; producer → queue). For infrastructure replication use Replicates To.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"service", "api", "website", "mobile"},
				Targets: []string{"database", "api", "service", "cloud_account"},
			},
		},
	},
	RelTypeStoresDataIn: {
		ID:          RelTypeStoresDataIn,
		Category:    "attack_path_analysis",
		Direct:      "Stores Data In",
		Inverse:     "Stores Data For",
		Description: "Data at-rest (service/app → database/bucket/data store).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"service", "api", "website"},
				Targets: []string{"database", "storage", "cloud_account"},
			},
			{
				Sources: []string{"k8s_workload"},
				Targets: []string{"database", "storage"},
			},
		},
	},
	RelTypeAuthenticatesTo: {
		ID:          RelTypeAuthenticatesTo,
		Category:    "attack_path_analysis",
		Direct:      "Authenticates To",
		Inverse:     "Authenticates",
		Description: "Authentication relationship (user/service → IdP/app/api).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"api", "service", "website", "mobile"},
				Targets: []string{"identity_provider", "service", "api"},
			},
			{
				Sources: []string{"k8s_workload"},
				Targets: []string{"identity_provider", "service"},
			},
		},
	},
	RelTypeGrantedTo: {
		ID:          RelTypeGrantedTo,
		Category:    "attack_path_analysis",
		Direct:      "Granted To",
		Inverse:     "Has Grant",
		Description: "IAM grant — a credential/role/policy is granted TO a principal (user, service, machine identity). Use for \"who is allowed to use this credential\". For \"what does this principal have access to\" use Has Access To.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"credential"},
				Targets: []string{"iam_user", "iam_role", "service_account", "service"},
			},
		},
	},
	RelTypeHasAccessTo: {
		ID:          RelTypeHasAccessTo,
		Category:    "attack_path_analysis",
		Direct:      "Has Access To",
		Inverse:     "Accessed By",
		Description: "IAM resource access — a principal/credential has been authorised to access a resource. The other half of the IAM model alongside Granted To. Use for \"what can this credential reach\".",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"credential", "iam_user", "iam_role", "service_account", "service"},
				Targets: []string{"cloud_account", "database", "api", "service", "k8s_cluster", "storage"},
			},
		},
	},
	RelTypeLoadBalances: {
		ID:          RelTypeLoadBalances,
		Category:    "attack_path_analysis",
		Direct:      "Load Balances",
		Inverse:     "Load Balanced By",
		Description: "Traffic distribution (load_balancer → service/web_app).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"load_balancer", "service", "cloud_account"},
				Targets: []string{"host", "k8s_workload", "service", "container"},
			},
		},
	},
	RelTypeProtectedBy: {
		ID:          RelTypeProtectedBy,
		Category:    "control_and_observability",
		Direct:      "Protected By",
		Inverse:     "Protects",
		Description: "Active security control that can block / mitigate / quarantine (WAF, EDR with prevention, IPS, CSPM with auto-remediation, runtime security agents). Use this when the tool can modify traffic/state, not just observe it. For pure observability use Monitors.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"website", "api", "service"},
				Targets: []string{"load_balancer", "service"},
			},
			{
				Sources: []string{"host", "compute"},
				Targets: []string{"service"},
			},
			{
				Sources: []string{"cloud_account"},
				Targets: []string{"service"},
			},
		},
	},
	RelTypeMonitors: {
		ID:          RelTypeMonitors,
		Category:    "control_and_observability",
		Direct:      "Monitors",
		Inverse:     "Monitored By",
		Description: "Passive observability — telemetry collection without blocking or modifying state (SIEM ingest, APM traces, log forwarding, vulnerability scanners). For tools that can take action use Protected By.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"service"},
				Targets: []string{"host", "k8s_cluster", "cloud_account", "api", "service", "database", "network"},
			},
		},
	},
	RelTypeManages: {
		ID:          RelTypeManages,
		Category:    "control_and_observability",
		Direct:      "Manages",
		Inverse:     "Managed By",
		Description: "Control-plane management — the source asset has CRUD authority over the target (cloud account manages its resources, k8s cluster manages its workloads, IaC stack manages provisioned assets). Different from Contains which is structural hierarchy.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{"cloud_account"},
				Targets: []string{"host", "database", "k8s_cluster", "network", "load_balancer"},
			},
			{
				Sources: []string{"k8s_cluster"},
				Targets: []string{"k8s_workload", "container"},
			},
		},
	},
}

// RelationshipCategory holds metadata about a relationship type category.
type RelationshipCategory struct {
	ID   string
	Name string
}

// RelationshipCategories is the ordered list of categories for the UI.
var RelationshipCategories = []RelationshipCategory{
	{ID: "attack_surface_mapping", Name: "Attack Surface Mapping"},
	{ID: "attack_path_analysis", Name: "Attack Path Analysis"},
	{ID: "control_and_observability", Name: "Control & Observability"},
}
