package sensor

// Code generated from configs/sensor-templates/*.tmpl; DO NOT EDIT BY HAND.
// The built-in templates are the fallback for a missing template file and
// must stay identical to the shipped files (TestTemplates_ShippedFilesMatchBuiltins).
// Regenerate after editing a .tmpl file:
//
//	go generate ./internal/app/sensor/

//go:generate go run ./gen_builtin_templates.go

var builtinTemplates = map[string]string{
	"yaml": `# Sensor configuration for {{slugify .Sensor.Name}}
# Generated by OpenCTEM at {{.GeneratedAt}}
#
# Save as sensor.yaml and run: openctemio-sensor -daemon -config sensor.yaml
# Environment variables (API_URL, API_KEY, SENSOR_TOOLS) override it.
#
# To customize this template, edit configs/sensor-templates/yaml.tmpl on the
# API host (/app/configs/sensor-templates/yaml.tmpl in the container image, or
# the directory set by SENSOR_CONFIG_TEMPLATES_DIR) — no frontend rebuild needed.

sensor:
  name: {{yamlQuote .Sensor.Name}}
  enable_commands: true
  heartbeat_interval: 30s

server:
  base_url: {{yamlQuote .BaseURL}}
  api_key: {{if .APIKey}}{{yamlQuote .APIKey}}{{else}}${API_KEY}{{end}}
  sensor_id: {{.Sensor.ID}}

# Results not yet accepted by the platform wait here; keep it on persistent
# storage so a restart or an outage loses nothing.
outbox:
  dir: /var/lib/openctem/outbox

# The sensor keeps its state, including the API key it renews on its own, in
# SENSOR_STATE_DIR (default /var/lib/openctem/state, else ~/.openctem). Keep
# that directory: without it the sensor starts with api_key above, which a
# renewal has retired.

scanners:
{{- with tools .Sensor.Tools}}
{{- range .}}
  - name: {{toScannerName .}}
    enabled: true
{{- end}}
{{- else}}
  - name: semgrep
    enabled: true
{{- end}}
`,
	"env": `# Environment variables for {{slugify .Sensor.Name}}
# Generated by OpenCTEM at {{.GeneratedAt}}
{{- if .APIKey}}
export API_URL={{shellQuote .BaseURL}}
export API_KEY={{shellQuote .APIKey}}
{{- else}}
# The API key is shown once, when the sensor is created or its key is rotated.
export API_URL={{shellQuote .BaseURL}}
export API_KEY='octs_...'
{{- end}}
{{- with toolList .Sensor.Tools}}
export SENSOR_TOOLS={{.}}
{{- end}}
{{- if .CACert}}
# The platform uses a private CA: install it (see the docker run instructions)
# and let the sensor trust it alongside the system roots.
export SSL_CERT_DIR=/etc/openctem/certs
{{- end}}
`,
	"docker": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor "{{$slug}}": docker run
# Generated by OpenCTEM at {{.GeneratedAt}}. Run it on the host that should scan.
# Edit configs/sensor-templates/docker.tmpl on the API host to change it.
{{- if not .APIKey}}
#
# The command reads the sensor's API key from OPENCTEM_API_KEY. The key is
# shown once, when the sensor is created or its key is rotated:
#   export OPENCTEM_API_KEY='octs_...'
{{- end}}
{{- if .CACert}}

# 1. Trust the platform's certificate authority (it uses a private CA).
sudo mkdir -p /etc/openctem/certs
sudo tee /etc/openctem/certs/openctem-root-ca.crt >/dev/null <<'OPENCTEM_CA'
{{.CACert}}OPENCTEM_CA
sudo chmod 0644 /etc/openctem/certs/openctem-root-ca.crt
{{- end}}
{{- if isDaemon .Sensor}}

# {{if .CACert}}2{{else}}1{{end}}. Install the sensor-local policy (the "Local policy" tab, saved as
# sensor-policy.yaml), reviewed by the owner of the network this sensor scans.
# The sensor refuses every job outside it; without the file it does not start.
# This needs a sensor release later than v0.8.0: v0.8.0 and older ignore the
# policy and the kill switch, and scan without a local policy.
sudo install -d -m 0755 /etc/openctem
sudo install -m 0644 sensor-policy.yaml /etc/openctem/sensor-policy.yaml

# {{if .CACert}}3{{else}}2{{end}}. Start the sensor. It connects out to the platform (no inbound port)
# and runs the scans the platform dispatches. Results that cannot be delivered
# yet wait in the {{$slug}}-outbox volume, so a restart or an outage loses nothing.
# The {{$slug}}-state volume keeps the sensor's state, including the API key
# it renews on its own: keep it with the container (a new container without it
# starts with the key above, which a renewal has retired). {{$slug}}-content
# caches scanner content (trivy DB, nuclei templates, semgrep rules) so a new
# container does not download it again; it can be deleted at any time.
# Hardened: read-only root filesystem, no capabilities, no privilege
# escalation (add --cap-add NET_RAW only for naabu SYN scans). /etc/openctem
# is mounted read-only: the policy, and the kill switch the host owner
# creates with sudo touch /etc/openctem/STOP.
docker run -d --name {{$slug}} --restart unless-stopped \
  --read-only --cap-drop ALL --security-opt no-new-privileges:true \
  --tmpfs /tmp --tmpfs /home/openctem --tmpfs /scan --tmpfs /cache --tmpfs /config \
  -e API_URL={{shellQuote .BaseURL}} \
{{- if .APIKey}}
  -e API_KEY={{shellQuote .APIKey}} \
{{- else}}
  -e API_KEY="${OPENCTEM_API_KEY:?export OPENCTEM_API_KEY first}" \
{{- end}}
{{- with toolList .Sensor.Tools}}
  -e SENSOR_TOOLS={{.}} \
{{- end}}
  -e SENSOR_LOCAL_POLICY=/etc/openctem/sensor-policy.yaml \
{{- if .Policy.AllowPrivate}}
  -e SENSOR_ALLOW_PRIVATE_TARGETS=1 \
{{- end}}
{{- if .CACert}}
  -e SSL_CERT_DIR=/etc/openctem/certs \
{{- end}}
  -v /etc/openctem:/etc/openctem:ro \
  -v {{$slug}}-outbox:/var/lib/openctem/outbox \
  -v {{$slug}}-state:/var/lib/openctem/state \
  -v {{$slug}}-content:/var/lib/openctem/content \
  {{.Image}}

# Check it: docker logs -f {{$slug}}   (the Sensors page shows it online
# within a minute)
{{- else}}

# {{if .CACert}}2. {{end}}Run one scan of the current directory and send the results (CI or a
# shell). Arguments after the image replace the default command.
docker run --rm \
  -e API_URL={{shellQuote .BaseURL}} \
{{- if .APIKey}}
  -e API_KEY={{shellQuote .APIKey}} \
{{- else}}
  -e API_KEY="${OPENCTEM_API_KEY:?export OPENCTEM_API_KEY first}" \
{{- end}}
{{- if .CACert}}
  -e SSL_CERT_DIR=/etc/openctem/certs \
  -v /etc/openctem/certs:/etc/openctem/certs:ro \
{{- end}}
  -v "$PWD":/scan \
  {{.Image}} \
  -tool {{firstTool .Sensor.Tools}} -target /scan -push
{{- end}}
`,
	"cli": `# Sensor binary commands for {{slugify .Sensor.Name}}
# Generated by OpenCTEM at {{.GeneratedAt}}
# Download: https://github.com/openctemio/sensor/releases ({{imageTag .Image}})

export API_URL={{shellQuote .BaseURL}}
{{- if .APIKey}}
export API_KEY={{shellQuote .APIKey}}
{{- else}}
export API_KEY="${OPENCTEM_API_KEY:?export OPENCTEM_API_KEY first}"
{{- end}}
{{- if .CACert}}
export SSL_CERT_DIR=/etc/openctem/certs
{{- end}}

# Long-running: run the scans the platform dispatches. The sensor keeps its
# state, including the API key it renews on its own, in SENSOR_STATE_DIR
# (default /var/lib/openctem/state when writable, else ~/.openctem).
./openctemio-sensor -daemon -enable-commands{{with toolList .Sensor.Tools}} -tools {{.}}{{end}}

# One-shot: scan a directory once and send the results
./openctemio-sensor -tool {{firstTool .Sensor.Tools}} -target . -push
`,
	"compose": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor "{{$slug}}": Docker Compose
# Generated by OpenCTEM at {{.GeneratedAt}}. Edit
# configs/sensor-templates/compose.tmpl on the API host to change it.
#
# In an empty directory on the host that should scan:
#   1. Put the sensor's API key in .env (kept out of this file):
{{- if .APIKey}}
#        printf '%s\n' 'OPENCTEM_API_KEY={{.APIKey}}' > .env && chmod 600 .env
{{- else}}
#        printf '%s\n' 'OPENCTEM_API_KEY=octs_...' > .env && chmod 600 .env
#      (the key is shown once, when the sensor is created or its key rotated)
{{- end}}
{{- if isDaemon .Sensor}}
#   2. Save the "Local policy" tab as policy/sensor-policy.yaml, after the
#      owner of the scanned network reviewed it (the sensor refuses every job
#      outside it; without the file it does not start), owned by root and
#      read-only:
#        sudo install -D -m 0644 -o root sensor-policy.yaml policy/sensor-policy.yaml
#   3. Save this file as compose.yaml and run: docker compose up -d
#   Kill switch (no job runs while the file exists): sudo touch policy/STOP
#   The policy and the kill switch need a sensor release later than v0.8.0;
#   v0.8.0 and older ignore them and scan without a local policy.
{{- else}}
#   2. Save this file as compose.yaml and run: docker compose up -d
{{- end}}
{{- if .CACert}}
#   The platform's private CA is embedded below (configs.content needs
#   Docker Compose 2.23.1 or later).
{{- end}}
services:
  sensor:
    image: {{.Image}}
    container_name: {{$slug}}
    restart: {{if isDaemon .Sensor}}unless-stopped{{else}}"no"{{end}}
{{- if not (isDaemon .Sensor)}}
    # A one-shot sensor: scans ./src once and sends the results.
    command: ["-tool", "{{firstTool .Sensor.Tools}}", "-target", "/scan", "-push"]
{{- end}}
{{- if isDaemon .Sensor}}
    # Hardened: read-only root filesystem, no capabilities, no privilege
    # escalation (add NET_RAW to cap_add only for naabu SYN scans).
    read_only: true
    cap_drop: [ALL]
    security_opt: ["no-new-privileges:true"]
    tmpfs: [/tmp, /home/openctem, /scan, /cache, /config]
{{- end}}
    environment:
      API_URL: {{yamlQuote .BaseURL}}
      API_KEY: ${OPENCTEM_API_KEY:?set OPENCTEM_API_KEY in .env}
{{- with toolList .Sensor.Tools}}
      SENSOR_TOOLS: {{yamlQuote .}}
{{- end}}
{{- if isDaemon .Sensor}}
      SENSOR_LOCAL_POLICY: /etc/openctem/policy/sensor-policy.yaml
      SENSOR_KILL_SWITCH_FILE: /etc/openctem/policy/STOP
{{- if .Policy.AllowPrivate}}
      SENSOR_ALLOW_PRIVATE_TARGETS: "1"
{{- end}}
{{- end}}
{{- if .CACert}}
      SSL_CERT_DIR: /etc/openctem/certs
{{- end}}
    volumes:
      - outbox:/var/lib/openctem/outbox
{{- if isDaemon .Sensor}}
      - state:/var/lib/openctem/state
      - content:/var/lib/openctem/content
      # The sensor-local policy and the kill switch, read-only.
      - ./policy:/etc/openctem/policy:ro
{{- end}}
{{- if not (isDaemon .Sensor)}}
      - ./src:/scan:ro
{{- end}}
{{- if .CACert}}
    configs:
      - source: openctem_ca
        target: /etc/openctem/certs/openctem-root-ca.crt
        mode: 0444
{{- end}}

volumes:
  # Results that cannot be delivered yet; a restart or an outage loses nothing.
  outbox:
{{- if isDaemon .Sensor}}
  # The sensor's state, including the API key it renews on its own. Keep it:
  # without it the sensor starts with the key in .env, which a renewal has
  # retired.
  state:
  # Scanner content cache (trivy DB, nuclei templates, semgrep rules); it can
  # be deleted, the sensor downloads it again.
  content:
{{- end}}
{{- if .CACert}}

configs:
  openctem_ca:
    content: |
{{indent 6 .CACert}}
{{- end}}
`,
	"kubernetes": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor "{{$slug}}": Kubernetes manifests
# Generated by OpenCTEM at {{.GeneratedAt}}. Edit
# configs/sensor-templates/kubernetes.tmpl on the API host to change it.
#
# Apply in the namespace the sensor should run in:
{{- if isDaemon .Sensor}}
#   1. Store the sensor-local policy (the "Local policy" tab, saved as
#      sensor-policy.yaml), reviewed by the owner of the scanned network. The
#      sensor refuses every job outside it; without it the pod does not start.
#      Keep write access to this ConfigMap with the network owner:
#        kubectl create configmap {{$slug}}-policy -n <namespace> --from-file=sensor-policy.yaml
#   2. kubectl apply -n <namespace> -f {{$slug}}.yaml
#   Kill switch: set "kill_switch: true" in the ConfigMap and restart the pod.
#   The policy needs a sensor release later than v0.8.0; v0.8.0 and older
#   ignore it and scan without a local policy.
{{- else}}
#   kubectl apply -n <namespace> -f {{$slug}}.yaml
{{- end}}
{{- if not .APIKey}}
# Replace octs_... below with the sensor's API key first (it is shown once,
# when the sensor is created or its key is rotated).
{{- end}}
apiVersion: v1
kind: Secret
metadata:
  name: {{$slug}}
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
type: Opaque
stringData:
  api-key: {{if .APIKey}}{{.APIKey}}{{else}}octs_...{{end}}
{{- if .CACert}}
  ca.crt: |
{{indent 4 .CACert}}
{{- end}}
{{- if isDaemon .Sensor}}
---
# Results that cannot be delivered yet; a restart or an outage loses nothing.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$slug}}-outbox
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
# The sensor's state, including the API key it renews on its own (the Secret
# above keeps the key it was installed with, which a renewal retires).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$slug}}-state
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 64Mi
---
# Scanner content cache (trivy DB, nuclei templates, semgrep rules), so a new
# pod does not download it again. Disposable: it can be deleted.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$slug}}-content
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$slug}}
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  # One sensor identity (one key) and one outbox: a single replica, and the
  # old pod stops before the new one starts.
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{$slug}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openctem-sensor
        app.kubernetes.io/instance: {{$slug}}
    spec:
      securityContext:
        # The image runs as uid/gid 999; fsGroup lets it write its volumes.
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sensor
          image: {{.Image}}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              # Add NET_RAW only for naabu SYN scans.
              drop: ["ALL"]
          env:
            - name: API_URL
              value: {{yamlQuote .BaseURL}}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{$slug}}
                  key: api-key
{{- with toolList .Sensor.Tools}}
            - name: SENSOR_TOOLS
              value: {{yamlQuote .}}
{{- end}}
            - name: SENSOR_LOCAL_POLICY
              value: /etc/openctem/policy/sensor-policy.yaml
{{- if .Policy.AllowPrivate}}
            - name: SENSOR_ALLOW_PRIVATE_TARGETS
              value: "1"
{{- end}}
{{- if .CACert}}
            - name: SSL_CERT_DIR
              value: /etc/openctem/certs
{{- end}}
          volumeMounts:
            - name: outbox
              mountPath: /var/lib/openctem/outbox
            - name: state
              mountPath: /var/lib/openctem/state
            - name: content
              mountPath: /var/lib/openctem/content
            - name: policy
              mountPath: /etc/openctem/policy
              readOnly: true
            # Writable scratch directories (the root filesystem is read-only).
            - name: tmp
              mountPath: /tmp
            - name: home
              mountPath: /home/openctem
            - name: scan
              mountPath: /scan
            - name: cache
              mountPath: /cache
            - name: config
              mountPath: /config
{{- if .CACert}}
            - name: ca
              mountPath: /etc/openctem/certs
              readOnly: true
{{- end}}
      volumes:
        - name: outbox
          persistentVolumeClaim:
            claimName: {{$slug}}-outbox
        - name: state
          persistentVolumeClaim:
            claimName: {{$slug}}-state
        - name: content
          persistentVolumeClaim:
            claimName: {{$slug}}-content
        - name: policy
          configMap:
            name: {{$slug}}-policy
            defaultMode: 0444
        - name: tmp
          emptyDir: {}
        - name: home
          emptyDir: {}
        - name: scan
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: config
          emptyDir: {}
{{- if .CACert}}
        - name: ca
          secret:
            secretName: {{$slug}}
            items:
              - key: ca.crt
                path: openctem-root-ca.crt
{{- end}}
{{- else}}
---
# A one-shot sensor: one scan, then the Job completes. Mount what it should
# scan at /scan (the emptyDir below is a placeholder).
apiVersion: batch/v1
kind: Job
metadata:
  name: {{$slug}}-scan
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openctem-sensor
        app.kubernetes.io/instance: {{$slug}}
    spec:
      restartPolicy: Never
      containers:
        - name: sensor
          image: {{.Image}}
          args: ["-tool", "{{firstTool .Sensor.Tools}}", "-target", "/scan", "-push"]
          env:
            - name: API_URL
              value: {{yamlQuote .BaseURL}}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{$slug}}
                  key: api-key
{{- if .CACert}}
            - name: SSL_CERT_DIR
              value: /etc/openctem/certs
{{- end}}
          volumeMounts:
            - name: scan
              mountPath: /scan
{{- if .CACert}}
            - name: ca
              mountPath: /etc/openctem/certs
              readOnly: true
{{- end}}
      volumes:
        - name: scan
          emptyDir: {}
{{- if .CACert}}
        - name: ca
          secret:
            secretName: {{$slug}}
            items:
              - key: ca.crt
                path: openctem-root-ca.crt
{{- end}}
{{- end}}
`,
	"helm": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor "{{$slug}}": Helm (the sensor bundled with the openctem chart)
# Generated by OpenCTEM at {{.GeneratedAt}}. Edit
# configs/sensor-templates/helm.tmpl on the API host to change it.
#
# Runs the sensor next to the platform, in the same cluster and namespace as
# the openctem release, talking to the API service directly. For a sensor in
# another network, use the Kubernetes or docker run instructions instead.
{{- if not (isDaemon .Sensor)}}
#
# The bundled sensor is a long-running one. This sensor runs one scan at a
# time (CI), so use the docker run or Kubernetes Job instructions instead.
{{- else}}
{{- if not .APIKey}}
# The key is shown once, when the sensor is created or its key is rotated:
#   export OPENCTEM_API_KEY='octs_...'
{{- end}}

# 1. Store the sensor's API key in a Secret (never in Helm values).
kubectl create secret generic {{$slug}}-key \
{{- if .APIKey}}
  --from-literal=api-key={{shellQuote .APIKey}}
{{- else}}
  --from-literal=api-key="${OPENCTEM_API_KEY:?export OPENCTEM_API_KEY first}"
{{- end}}

# 2. Save the "Local policy" tab as sensor-policy.yaml, reviewed by the owner
#    of the scanned network: the sensor refuses every job outside it.
#    This needs a sensor release later than v0.8.0; v0.8.0 and older ignore
#    the policy and scan without one.

# 3. Turn the bundled sensor on (release "openctem"; use yours). Chart 0.11.0
#    or later: the sensor runs hardened (non-root, read-only root filesystem,
#    no capabilities, seccomp RuntimeDefault) and mounts the policy read-only.
helm upgrade openctem openctem/openctem --reuse-values \
  --set sensor.enabled=true \
  --set sensor.mode=daemon \
  --set sensor.image.tag={{imageTag .Image}} \
  --set sensor.existingSecret={{$slug}}-key \
{{- with toolList .Sensor.Tools}}
  --set-string 'sensor.tools={{replaceComma .}}' \
{{- end}}
  --set sensor.outbox.persistence.enabled=true \
  --set sensor.state.persistence.enabled=true \
  --set sensor.content.persistence.enabled=true \
  --set sensor.localPolicy.enabled=true \
  --set-file sensor.localPolicy.policy=sensor-policy.yaml
{{- end}}
`,
	"policy": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor-local policy for "{{$slug}}" (RFC-040 §5.7).
# Generated by OpenCTEM at {{.GeneratedAt}} as a starting point. Edit
# configs/sensor-templates/policy.tmpl on the API host to change it.
#
# The owner of the network this sensor scans reviews and edits this file,
# then installs it on the sensor host, owned by root and read-only:
#   sudo install -d -m 0755 /etc/openctem
#   sudo install -m 0644 sensor-policy.yaml /etc/openctem/sensor-policy.yaml
# The sensor refuses every job outside it, whatever the platform sends, and
# reports only its digest and a summary. The platform cannot change it.
# Requires a sensor release later than v0.8.0: v0.8.0 and older ignore this
# file (and the kill switch) and scan without a local policy.
# Every key: https://github.com/openctemio/sensor/blob/main/docs/LOCAL_POLICY.md
apiVersion: openctem.io/sensor-policy/v1

targets:
{{- if .Policy.Open}}
  # This sensor is in the default zone, which scans public targets that no
  # range lists, so there is no allow list: any target outside "deny" and
  # the built-in deny list (loopback, link-local and metadata, CGNAT,
  # multicast) may be scanned. List the ranges and domains to narrow it.
{{- range .Policy.Ranges}}
  #   {{.}}
{{- end}}
{{- else if .Policy.Ranges}}
  # The ranges of this sensor's scan zones. Add host names or *.domain
  # entries the sensor may also scan.
  allow:
{{- range .Policy.Ranges}}
    - {{yamlQuote .}}
{{- end}}
{{- else}}
  # What this sensor may scan: CIDRs, IPs, host names and *.domain. This
  # sensor has no scan zone yet; list its ranges. Without "allow", any target
  # outside "deny" and the built-in deny list may be scanned.
  # allow:
  #   - 203.0.113.0/24
  #   - "*.example.com"
{{- end}}
  # Never scanned, even when "allow" matches (every address a name resolves
  # to is checked).
  deny: []
  # RFC 1918 / ULA ranges. The sensor must also run with
  # SENSOR_ALLOW_PRIVATE_TARGETS=1: the policy only narrows.
  allow_private: {{.Policy.AllowPrivate}}
{{- with tools .Sensor.Tools}}

tools:
  # The tools this sensor may run.
  allow:
{{- range .}}
    - {{yamlQuote .}}
{{- end}}
{{- end}}

# Platform-supplied custom templates and out-of-band callbacks (nuclei
# interactsh) stay off unless the network owner turns them on.
allow_custom_templates: false
allow_interactsh: false

# While this file exists the sensor runs no job and reports "paused by local
# policy": sudo touch /etc/openctem/STOP (remove it to resume).
kill_switch_file: /etc/openctem/STOP
`,
}
