// Code generated by api/cmd/gen-modules from api/configs/modules.yaml. DO NOT EDIT.
// Run `make generate-modules` in api/ after changing the registry.

export type ModuleRelease = 'released' | 'beta' | 'coming_soon' | 'deprecated'

export interface ModuleDefinition {
  id: string
  name: string
  core: boolean
  parent?: string
  release: ModuleRelease
  userFacing: boolean
  permission?: string
}

export const MODULE_REGISTRY: readonly ModuleDefinition[] = [
  { id: 'dashboard', name: 'Dashboard', core: true, release: 'released', userFacing: true, permission: 'dashboard:read' },
  { id: 'assets', name: 'Assets', core: true, release: 'released', userFacing: true, permission: 'assets:read' },
  { id: 'findings', name: 'Findings', core: true, release: 'released', userFacing: true, permission: 'findings:read' },
  { id: 'scans', name: 'Scans', core: true, release: 'released', userFacing: true, permission: 'scans:read' },
  { id: 'attack_surface', name: 'Attack Surface', core: false, release: 'released', userFacing: true, permission: 'assets:read' },
  { id: 'scope_config', name: 'Scope Config', core: false, release: 'released', userFacing: true, permission: 'attack_surface:scope:read' },
  { id: 'business_services', name: 'Business Services', core: false, release: 'released', userFacing: true, permission: 'ctem:business_services:read' },
  { id: 'ctem_cycles', name: 'CTEM Cycles', core: false, release: 'released', userFacing: true, permission: 'ctem:cycles:read' },
  { id: 'attacker_profiles', name: 'Attacker Profiles', core: false, release: 'released', userFacing: true, permission: 'ctem:attacker_profiles:read' },
  { id: 'credentials', name: 'Credentials', core: false, release: 'released', userFacing: true, permission: 'findings:credentials:read' },
  { id: 'relationships', name: 'Relationships', core: false, release: 'released', userFacing: true, permission: 'assets:read' },
  { id: 'scanner_templates', name: 'Scanner Templates', core: false, release: 'released', userFacing: true, permission: 'scans:templates:read' },
  { id: 'business_units', name: 'Business Units', core: false, release: 'released', userFacing: true, permission: 'assets:read' },
  { id: 'components', name: 'Components', core: false, release: 'released', userFacing: true, permission: 'assets:components:read' },
  { id: 'template_sources', name: 'Template Sources', core: false, release: 'released', userFacing: true, permission: 'scans:templates:read' },
  { id: 'branches', name: 'Branches', core: false, release: 'released', userFacing: false, permission: 'assets:read' },
  { id: 'crown_jewels', name: 'Crown Jewels', core: false, release: 'released', userFacing: true, permission: 'assets:read' },
  { id: 'scan_workflows', name: 'Scan Workflows', core: false, release: 'released', userFacing: true, permission: 'scans:workflows:read' },
  { id: 'threat_model', name: 'Threat Model', core: false, release: 'released', userFacing: true, permission: 'assets:read' },
  { id: 'threat_intel', name: 'Threat Intel', core: false, release: 'released', userFacing: true, permission: 'threat_intel:read' },
  { id: 'exposures', name: 'Exposures', core: false, release: 'released', userFacing: true, permission: 'findings:exposures:read' },
  { id: 'ai_triage', name: 'AI Triage', core: false, release: 'released', userFacing: false, permission: 'ai_triage:read' },
  { id: 'ai_triage.bulk', name: 'Bulk Triage', core: false, parent: 'ai_triage', release: 'released', userFacing: false },
  { id: 'ai_triage.auto', name: 'Auto Triage', core: false, parent: 'ai_triage', release: 'released', userFacing: false },
  { id: 'ai_triage.workflow', name: 'Workflow Triage', core: false, parent: 'ai_triage', release: 'released', userFacing: false },
  { id: 'ai_triage.byok', name: 'BYOK Mode', core: false, parent: 'ai_triage', release: 'released', userFacing: false },
  { id: 'ai_triage.agent', name: 'Agent Mode', core: false, parent: 'ai_triage', release: 'released', userFacing: false },
  { id: 'ai_triage.custom_prompts', name: 'Custom Prompts', core: false, parent: 'ai_triage', release: 'released', userFacing: false },
  { id: 'sla', name: 'SLA Management', core: true, release: 'released', userFacing: true, permission: 'settings:sla:read' },
  { id: 'priority_rules', name: 'Priority Rules', core: false, release: 'released', userFacing: true, permission: 'findings:read' },
  { id: 'risk_analysis', name: 'Risk Analysis', core: false, release: 'released', userFacing: true, permission: 'findings:read' },
  { id: 'business_impact', name: 'Business Impact', core: false, release: 'released', userFacing: true, permission: 'ctem:business_services:read' },
  { id: 'risk_scoring', name: 'Risk Scoring', core: false, release: 'released', userFacing: true, permission: 'settings:read' },
  { id: 'pentest', name: 'Penetration Testing', core: false, release: 'released', userFacing: true, permission: 'pentest:campaigns:read' },
  { id: 'attack_simulation', name: 'Attack Simulation', core: false, release: 'beta', userFacing: true },
  { id: 'control_testing', name: 'Control Testing', core: false, release: 'beta', userFacing: true },
  { id: 'compensating_controls', name: 'Compensating Controls', core: false, release: 'released', userFacing: true, permission: 'ctem:compensating_controls:read' },
  { id: 'remediation', name: 'Remediation', core: false, release: 'released', userFacing: true, permission: 'findings:remediation:read' },
  { id: 'suppressions', name: 'Suppressions', core: false, release: 'released', userFacing: false, permission: 'findings:suppressions:read' },
  { id: 'workflows', name: 'Workflows', core: false, release: 'released', userFacing: true, permission: 'findings:workflows:read' },
  { id: 'reports', name: 'Reports', core: false, release: 'released', userFacing: true, permission: 'reports:read' },
  { id: 'audit', name: 'Audit', core: true, release: 'released', userFacing: true, permission: 'audit:read' },
  { id: 'ctem_maturity', name: 'CTEM Maturity', core: false, release: 'released', userFacing: true, permission: 'dashboard:read' },
  { id: 'executive_summary', name: 'Executive Summary', core: false, release: 'released', userFacing: true, permission: 'reports:read' },
  { id: 'mitre_coverage', name: 'MITRE Coverage', core: false, release: 'released', userFacing: true, permission: 'threat_intel:read' },
  { id: 'sbom_export', name: 'SBOM Export', core: false, release: 'released', userFacing: true, permission: 'assets:components:read' },
  { id: 'integrations', name: 'Integrations', core: true, release: 'released', userFacing: true, permission: 'integrations:read' },
  { id: 'integrations.scm', name: 'SCM Integrations', core: false, parent: 'integrations', release: 'released', userFacing: false },
  { id: 'integrations.notifications', name: 'Notification Channels', core: true, parent: 'integrations', release: 'released', userFacing: false },
  { id: 'integrations.ticketing', name: 'Ticketing', core: false, parent: 'integrations', release: 'released', userFacing: false },
  { id: 'integrations.cloud', name: 'Cloud Providers', core: false, parent: 'integrations', release: 'released', userFacing: false },
  { id: 'integrations.siem', name: 'SIEM', core: false, parent: 'integrations', release: 'released', userFacing: false },
  { id: 'integrations.scanners', name: 'Scanners', core: false, parent: 'integrations', release: 'released', userFacing: false },
  { id: 'integrations.api', name: 'API Integrations', core: false, parent: 'integrations', release: 'released', userFacing: false },
  { id: 'integrations.pipelines', name: 'Pipeline Integrations', core: false, parent: 'integrations', release: 'released', userFacing: false },
  { id: 'sensors', name: 'Sensors', core: true, release: 'released', userFacing: false, permission: 'sensors:read' },
  { id: 'team', name: 'Team', core: true, release: 'released', userFacing: true, permission: 'team:read' },
  { id: 'groups', name: 'Groups', core: true, release: 'released', userFacing: false, permission: 'team:groups:read' },
  { id: 'roles', name: 'Roles', core: true, release: 'released', userFacing: true, permission: 'team:roles:read' },
  { id: 'settings', name: 'Settings', core: true, release: 'released', userFacing: true, permission: 'settings:read' },
  { id: 'api_keys', name: 'API Keys', core: true, release: 'released', userFacing: false, permission: 'integrations:api_keys:read' },
  { id: 'notification_settings', name: 'Notifications', core: true, release: 'released', userFacing: false, permission: 'integrations:notifications:read' },
  { id: 'tools', name: 'Tools', core: false, release: 'released', userFacing: false, permission: 'scans:tools:read' },
  { id: 'scan_profiles', name: 'Scan Profiles', core: false, release: 'released', userFacing: false, permission: 'scans:profiles:read' },
  { id: 'iocs', name: 'IOCs', core: false, release: 'released', userFacing: false, permission: 'threat_intel:read' },
  { id: 'compliance', name: 'Compliance', core: false, release: 'released', userFacing: true, permission: 'compliance:frameworks:read' },
]

export type ModuleId =
  | 'dashboard'
  | 'assets'
  | 'findings'
  | 'scans'
  | 'attack_surface'
  | 'scope_config'
  | 'business_services'
  | 'ctem_cycles'
  | 'attacker_profiles'
  | 'credentials'
  | 'relationships'
  | 'scanner_templates'
  | 'business_units'
  | 'components'
  | 'template_sources'
  | 'branches'
  | 'crown_jewels'
  | 'scan_workflows'
  | 'threat_model'
  | 'threat_intel'
  | 'exposures'
  | 'ai_triage'
  | 'ai_triage.bulk'
  | 'ai_triage.auto'
  | 'ai_triage.workflow'
  | 'ai_triage.byok'
  | 'ai_triage.agent'
  | 'ai_triage.custom_prompts'
  | 'sla'
  | 'priority_rules'
  | 'risk_analysis'
  | 'business_impact'
  | 'risk_scoring'
  | 'pentest'
  | 'attack_simulation'
  | 'control_testing'
  | 'compensating_controls'
  | 'remediation'
  | 'suppressions'
  | 'workflows'
  | 'reports'
  | 'audit'
  | 'ctem_maturity'
  | 'executive_summary'
  | 'mitre_coverage'
  | 'sbom_export'
  | 'integrations'
  | 'integrations.scm'
  | 'integrations.notifications'
  | 'integrations.ticketing'
  | 'integrations.cloud'
  | 'integrations.siem'
  | 'integrations.scanners'
  | 'integrations.api'
  | 'integrations.pipelines'
  | 'sensors'
  | 'team'
  | 'groups'
  | 'roles'
  | 'settings'
  | 'api_keys'
  | 'notification_settings'
  | 'tools'
  | 'scan_profiles'
  | 'iocs'
  | 'compliance'

/** Every module id of the registry. */
export const MODULE_IDS: ReadonlySet<string> = new Set(MODULE_REGISTRY.map((m) => m.id))

/** Modules that are always on. */
export const CORE_MODULE_IDS: ReadonlySet<string> = new Set(
  MODULE_REGISTRY.filter((m) => m.core).map((m) => m.id)
)
