// Code generated by cmd/gen-modules from configs/modules.yaml. DO NOT EDIT.

package module

// Module ids (configs/modules.yaml).
const (
	ModuleDashboard                 = "dashboard"
	ModuleAssets                    = "assets"
	ModuleFindings                  = "findings"
	ModuleScans                     = "scans"
	ModuleAttackSurface             = "attack_surface"
	ModuleScopeConfig               = "scope_config"
	ModuleBusinessServices          = "business_services"
	ModuleCTEMCycles                = "ctem_cycles"
	ModuleAttackerProfiles          = "attacker_profiles"
	ModuleCredentials               = "credentials"
	ModuleRelationships             = "relationships"
	ModuleScannerTemplates          = "scanner_templates"
	ModuleBusinessUnits             = "business_units"
	ModuleComponents                = "components"
	ModuleTemplateSources           = "template_sources"
	ModuleBranches                  = "branches"
	ModuleCrownJewels               = "crown_jewels"
	ModuleScanWorkflows             = "scan_workflows"
	ModuleThreatModel               = "threat_model"
	ModuleThreatIntel               = "threat_intel"
	ModuleExposures                 = "exposures"
	ModuleAITriage                  = "ai_triage"
	ModuleAITriageBulk              = "ai_triage.bulk"
	ModuleAITriageAuto              = "ai_triage.auto"
	ModuleAITriageWorkflow          = "ai_triage.workflow"
	ModuleAITriageBYOK              = "ai_triage.byok"
	ModuleAITriageAgent             = "ai_triage.agent"
	ModuleAITriageCustomPrompts     = "ai_triage.custom_prompts"
	ModuleSLA                       = "sla"
	ModulePriorityRules             = "priority_rules"
	ModuleRiskAnalysis              = "risk_analysis"
	ModuleBusinessImpact            = "business_impact"
	ModuleRiskScoring               = "risk_scoring"
	ModulePentest                   = "pentest"
	ModuleAttackSimulation          = "attack_simulation"
	ModuleControlTesting            = "control_testing"
	ModuleCompensatingControls      = "compensating_controls"
	ModuleRemediation               = "remediation"
	ModuleSuppressions              = "suppressions"
	ModuleWorkflows                 = "workflows"
	ModuleReports                   = "reports"
	ModuleAudit                     = "audit"
	ModuleCTEMMaturity              = "ctem_maturity"
	ModuleExecutiveSummary          = "executive_summary"
	ModuleMITRECoverage             = "mitre_coverage"
	ModuleSBOMExport                = "sbom_export"
	ModuleIntegrations              = "integrations"
	ModuleIntegrationsSCM           = "integrations.scm"
	ModuleIntegrationsNotifications = "integrations.notifications"
	ModuleIntegrationsTicketing     = "integrations.ticketing"
	ModuleIntegrationsCloud         = "integrations.cloud"
	ModuleIntegrationsSIEM          = "integrations.siem"
	ModuleIntegrationsScanners      = "integrations.scanners"
	ModuleIntegrationsAPI           = "integrations.api"
	ModuleIntegrationsPipelines     = "integrations.pipelines"
	ModuleSensors                   = "sensors"
	ModuleTeam                      = "team"
	ModuleGroups                    = "groups"
	ModuleRoles                     = "roles"
	ModuleSettings                  = "settings"
	ModuleAPIKeys                   = "api_keys"
	ModuleNotificationSettings      = "notification_settings"
	ModuleTools                     = "tools"
	ModuleScanProfiles              = "scan_profiles"
	ModuleIOCs                      = "iocs"
	ModuleCompliance                = "compliance"
)

// Registry is every module, top-level modules in display order, each
// followed by its sub-modules.
var Registry = []Definition{
	{
		ID: ModuleDashboard, Slug: "dashboard", Name: "Dashboard",
		Description: "Main dashboard with security overview and statistics",
		Icon:        "LayoutDashboard",
		Category:    "core", DisplayOrder: 1, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "dashboard:read",
	},
	{
		ID: ModuleAssets, Slug: "assets", Name: "Assets",
		Description: "The asset inventory, asset groups and every asset type",
		Icon:        "Server",
		Category:    "core", DisplayOrder: 2, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "assets:read",
		MCP:        []string{"list_assets"},
		Jobs:       []string{"AssetIdentityBackfillController", "AssetChangeTimelineController", "AssetLifecycleController", "AssetPurgeController", "OwnerResolutionController", "DataExpirationController", "DomainReverifyController"},
	},
	{
		ID: ModuleFindings, Slug: "findings", Name: "Findings",
		Description: "Findings, approvals and exceptions, with SLA deadlines and priority classes",
		Icon:        "AlertTriangle",
		Category:    "core", DisplayOrder: 3, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "findings:read",
		MCP:        []string{"list_findings", "get_finding", "finding_stats", "list_active_cves", "explain_finding_priority", "list_remediation_groups"},
		Jobs:       []string{"ApprovalExpirationController", "PriorityReclassifyController", "PriorityReclassifySweepController", "PriorityAuditRetentionController", "EvidenceRetentionController", "ScannerOutputRetentionController", "RiskSnapshotController", "CTEMIDRefreshController", "IngestWorkerController", "JobRecoveryController", "RetestScheduler", "ThreatIntelRefreshController", "VulnMatchController", "VulnFeedImportController"},
	},
	{
		ID: ModuleScans, Slug: "scans", Name: "Scans",
		Description: "Scans, Scanning settings (Sensors, Profiles, Tools, Capabilities, Templates, Sources, Secret Store)",
		Icon:        "Search",
		Category:    "core", DisplayOrder: 4, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "scans:read",
		Jobs:       []string{"CoverageScheduler", "OneOffScanArchiveController", "QueuePriorityController", "ScanRetryController", "ScanTimeoutController", "ScanWindowClosingController", "StalledRunRepairController", "CIAlertsController", "CIRetentionController", "CommandEventRetentionController", "CommandLogRetentionController", "WebSurfaceRetentionController"},
	},
	{
		ID: ModuleAttackSurface, Slug: "attack-surface", Name: "Attack Surface",
		Description: "External attack surface overview — what an adversary sees before touching the network",
		Icon:        "Target",
		Category:    "scoping", DisplayOrder: 5, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "assets:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "attack surface is computed from assets"},
		},
		Routes: []string{"/api/v1/attack-surface", "/api/v1/easm"},
		MCP:    []string{"get_exposure_chains"},
		Jobs:   []string{"CertMonitorController", "EASMDNSController", "GraphEnrichmentController", "ScopeJoinController"},
	},
	{
		ID: ModuleScopeConfig, Slug: "scope-config", Name: "Scope Config",
		Description: "CTEM scope — which assets are in scope for prioritisation and reporting",
		Icon:        "Sliders",
		Category:    "scoping", DisplayOrder: 6, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "attack_surface:scope:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "scope rules select assets"},
		},
		Routes: []string{"/api/v1/scope", "/api/v1/programs"},
		Jobs:   []string{"ProgramAssignmentController", "ProgramFeedController", "ProgramSyncController", "ScopeAttestationController"},
	},
	{
		ID: ModuleBusinessServices, Slug: "business-services", Name: "Business Services",
		Description: "Map business services to the underlying assets that power them",
		Icon:        "Building",
		Category:    "scoping", DisplayOrder: 7, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "ctem:business_services:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "services map to underlying assets"},
		},
		Routes: []string{"/api/v1/business-services"},
	},
	{
		ID: ModuleCTEMCycles, Slug: "ctem-cycles", Name: "CTEM Cycles",
		Description: "Gartner CTEM lifecycle — scoping, discovery, prioritisation, validation, mobilisation",
		Icon:        "RotateCcw",
		Category:    "scoping", DisplayOrder: 8, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "ctem:cycles:read",
		Depends: []Dependency{
			{ModuleID: ModuleScopeConfig, Type: DependencyHard, Reason: "cycles operate on a defined scope"},
			{ModuleID: ModuleFindings, Type: DependencySoft, Reason: "cycle phases reference findings progress"},
		},
		Routes: []string{"/api/v1/ctem-cycles"},
	},
	{
		ID: ModuleAttackerProfiles, Slug: "attacker-profiles", Name: "Attacker Profiles",
		Description: "Threat actor profiles used to drive attack simulation + prioritisation scoring",
		Icon:        "Swords",
		Category:    "scoping", DisplayOrder: 9, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "ctem:attacker_profiles:read",
		Routes:     []string{"/api/v1/attacker-profiles"},
	},
	{
		ID: ModuleCredentials, Slug: "credentials", Name: "Credentials",
		Description: "Leaked credentials monitoring and detection",
		Icon:        "Key",
		Category:    "discovery", DisplayOrder: 10, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "findings:credentials:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "leaked credentials are scoped to assets"},
		},
		Routes: []string{"/api/v1/credentials"},
	},
	{
		ID: ModuleRelationships, Slug: "relationships", Name: "Relationships",
		Description: "Asset-to-asset relationships for attack-path modelling",
		Icon:        "Link",
		Category:    "scoping", DisplayOrder: 10, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "assets:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "relationships are between assets"},
		},
		Routes: []string{"/api/v1/relationships", "/api/v1/assets/{}/relationships"},
	},
	{
		ID: ModuleScannerTemplates, Slug: "scanner-templates", Name: "Scanner Templates",
		Description: "Catalogue of Nuclei / Betterleaks / Semgrep templates",
		Icon:        "FileCode",
		Category:    "settings", DisplayOrder: 10, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "scans:templates:read",
		Depends: []Dependency{
			{ModuleID: ModuleScans, Type: DependencyHard, Reason: "templates are consumed by scans"},
		},
		Routes: []string{"/api/v1/scanner-templates", "/api/v1/content-packs", "/api/v1/platform-content-packs"},
	},
	{
		ID: ModuleBusinessUnits, Slug: "business-units", Name: "Business Units",
		Description: "Organisational units that group assets for ownership, criticality and reporting",
		Icon:        "Building2",
		Category:    "scoping", DisplayOrder: 11, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "assets:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "business units group underlying assets"},
		},
		Routes: []string{"/api/v1/business-units"},
	},
	{
		ID: ModuleComponents, Slug: "components", Name: "Components",
		Description: "Software Components (SBOM), Ecosystems, Licenses, and vulnerability tracking",
		Icon:        "Package",
		Category:    "discovery", DisplayOrder: 11, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "assets:components:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "components belong to assets (repos, images, runtimes)"},
		},
		Routes: []string{"/api/v1/components", "/api/v1/assets/{}/components", "/api/v1/assets/{}/dependency-paths", "/api/v1/assets/{}/dependency-graph", "/api/v1/vex-statements"},
		Jobs:   []string{"VEXStatementExpiryController"},
	},
	{
		ID: ModuleTemplateSources, Slug: "template-sources", Name: "Template Sources",
		Description: "Upstream git sources that templates are synced from",
		Icon:        "Database",
		Category:    "settings", DisplayOrder: 11, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "scans:templates:read",
		Depends: []Dependency{
			{ModuleID: ModuleScannerTemplates, Type: DependencyHard, Reason: "sources feed the template catalogue"},
		},
		Routes: []string{"/api/v1/template-sources"},
	},
	{
		ID: ModuleBranches, Slug: "branches", Name: "Branches",
		Description: "Code branches",
		Icon:        "GitBranch",
		Category:    "discovery", DisplayOrder: 12, Release: ReleaseStatusReleased,
		Permission: "assets:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "branches belong to repository assets"},
			{ModuleID: ModuleComponents, Type: DependencySoft, Reason: "branch views surface component inventories per branch"},
		},
		Routes: []string{"/api/v1/repositories/{}/branches"},
	},
	{
		ID: ModuleCrownJewels, Slug: "crown-jewels", Name: "Crown Jewels",
		Description: "Business-critical assets flagged for heightened prioritisation and monitoring",
		Icon:        "Crown",
		Category:    "scoping", DisplayOrder: 12, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "assets:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "crown jewels are assets flagged as business-critical"},
		},
	},
	{
		ID: ModuleScanWorkflows, Slug: "scan-workflows", Name: "Scan Workflows",
		Description: "Scan workflows: the steps a scan runs, chained by what each step finds",
		Icon:        "GitBranch",
		Category:    "settings", DisplayOrder: 12, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "scans:workflows:read",
		Depends: []Dependency{
			{ModuleID: ModuleScans, Type: DependencyHard, Reason: "scan workflows are what scans run"},
			{ModuleID: ModuleScannerTemplates, Type: DependencySoft, Reason: "scan workflow steps typically run templates"},
		},
		Routes: []string{"/api/v1/scan-workflows"},
	},
	{
		ID: ModuleThreatModel, Slug: "threat-model", Name: "Threat Model",
		Description: "Continuous threat modelling derived from the asset graph and findings",
		Icon:        "Crosshair",
		Category:    "scoping", DisplayOrder: 13, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "assets:read",
		Depends: []Dependency{
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "threat models are derived from the asset graph"},
			{ModuleID: ModuleFindings, Type: DependencySoft, Reason: "threat-model coverage reflects findings on in-scope assets"},
		},
		Routes: []string{"/api/v1/threat-models"},
		Jobs:   []string{"ThreatModelRefreshController"},
	},
	{
		ID: ModuleThreatIntel, Slug: "threat_intel", Name: "Threat Intel",
		Description: "Threat actors and the threat intelligence workspace",
		Icon:        "Radar",
		Category:    "prioritization", DisplayOrder: 20, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "threat_intel:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "threat intel enriches findings"},
		},
		Routes: []string{"/api/v1/threat-actors"},
	},
	{
		ID: ModuleExposures, Slug: "exposures", Name: "Exposures",
		Description: "Exposure management and non-CVE security issues",
		Icon:        "ShieldAlert",
		Category:    "prioritization", DisplayOrder: 21, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "findings:exposures:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "an exposure is a finding in a specific lifecycle state"},
		},
		Routes: []string{"/api/v1/exposures"},
	},
	{
		ID: ModuleAITriage, Slug: "ai_triage", Name: "AI Triage",
		Description: "AI-powered vulnerability triage (Bulk, Auto, Workflow, BYOK, Agent modes)",
		Icon:        "Brain",
		Category:    "prioritization", DisplayOrder: 22, Release: ReleaseStatusReleased,
		Permission: "ai_triage:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "triage operates on findings"},
			{ModuleID: ModuleThreatIntel, Type: DependencySoft, Reason: "triage uses KEV/EPSS context when scoring"},
		},
		Routes: []string{"/api/v1/findings/{}/ai-triage", "/api/v1/findings/ai-triage"},
	},
	{
		ID: ModuleAITriageBulk, Slug: "ai_triage_bulk", Name: "Bulk Triage",
		Description: "Bulk triage operations",
		Icon:        "Layers",
		Category:    "prioritization", DisplayOrder: 1, Release: ReleaseStatusReleased,
		Parent: ModuleAITriage,
	},
	{
		ID: ModuleAITriageAuto, Slug: "ai_triage_auto", Name: "Auto Triage",
		Description: "Auto-triage on finding creation",
		Icon:        "Zap",
		Category:    "prioritization", DisplayOrder: 2, Release: ReleaseStatusReleased,
		Parent: ModuleAITriage,
	},
	{
		ID: ModuleAITriageWorkflow, Slug: "ai_triage_workflow", Name: "Workflow Triage",
		Description: "Workflow triggers and actions",
		Icon:        "GitPullRequest",
		Category:    "prioritization", DisplayOrder: 3, Release: ReleaseStatusReleased,
		Parent: ModuleAITriage,
	},
	{
		ID: ModuleAITriageBYOK, Slug: "ai_triage_byok", Name: "BYOK Mode",
		Description: "Bring Your Own Key mode",
		Icon:        "Key",
		Category:    "prioritization", DisplayOrder: 4, Release: ReleaseStatusReleased,
		Parent: ModuleAITriage,
	},
	{
		ID: ModuleAITriageAgent, Slug: "ai_triage_agent", Name: "Agent Mode",
		Description: "Self-hosted Agent mode",
		Icon:        "Cpu",
		Category:    "prioritization", DisplayOrder: 5, Release: ReleaseStatusReleased,
		Parent: ModuleAITriage,
	},
	{
		ID: ModuleAITriageCustomPrompts, Slug: "ai_triage_custom_prompts", Name: "Custom Prompts",
		Description: "Custom prompt templates",
		Icon:        "FileText",
		Category:    "prioritization", DisplayOrder: 6, Release: ReleaseStatusReleased,
		Parent: ModuleAITriage,
	},
	{
		ID: ModuleSLA, Slug: "sla", Name: "SLA Management",
		Description: "SLA policies for remediation time tracking",
		Icon:        "Clock",
		Category:    "prioritization", DisplayOrder: 23, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "settings:sla:read",
		Jobs:       []string{"SLAEscalationController"},
	},
	{
		ID: ModulePriorityRules, Slug: "priority-rules", Name: "Priority Rules",
		Description: "Declarative priority classification rules (P0..P3)",
		Icon:        "Sliders",
		Category:    "prioritization", DisplayOrder: 24, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "findings:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "rules classify findings"},
			{ModuleID: ModuleThreatIntel, Type: DependencySoft, Reason: "rule conditions often reference KEV/EPSS"},
		},
		Routes: []string{"/api/v1/priority-rules"},
	},
	{
		ID: ModuleRiskAnalysis, Slug: "risk-analysis", Name: "Risk Analysis",
		Description: "Aggregate risk dashboards across assets + findings",
		Icon:        "BarChart",
		Category:    "prioritization", DisplayOrder: 25, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "findings:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "risk scoring reads finding severity + exposure"},
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "per-asset risk requires the asset inventory"},
		},
	},
	{
		ID: ModuleBusinessImpact, Slug: "business-impact", Name: "Business Impact",
		Description: "Business impact scoring weighted by business-services mapping",
		Icon:        "Building",
		Category:    "prioritization", DisplayOrder: 26, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "ctem:business_services:read",
		Depends: []Dependency{
			{ModuleID: ModuleBusinessServices, Type: DependencyHard, Reason: "impact scoring is weighted by business-service mapping"},
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "impact is computed from finding severity × service weight"},
		},
	},
	{
		ID: ModuleRiskScoring, Slug: "risk-scoring", Name: "Risk Scoring",
		Description: "Risk scoring config — CVSS / EPSS / KEV / custom weights",
		Icon:        "TrendingUp",
		Category:    "prioritization", DisplayOrder: 27, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "settings:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "risk scoring operates on findings"},
		},
	},
	{
		ID: ModulePentest, Slug: "pentest", Name: "Penetration Testing",
		Description: "Penetration testing campaigns, findings, retests and reports",
		Icon:        "Crosshair",
		Category:    "validation", DisplayOrder: 30, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "pentest:campaigns:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "pentest campaigns produce findings"},
		},
		Routes: []string{"/api/v1/pentest"},
		MCP:    []string{"get_campaign", "list_campaign_findings", "get_pentest_finding", "list_retests", "list_finding_templates", "campaign_report_stats", "exec_summary", "finding_writeup", "remediation_guidance", "attack_narrative"},
	},
	{
		ID: ModuleAttackSimulation, Slug: "attack-simulation", Name: "Attack Simulation",
		Description: "Breach & Attack Simulation (BAS) — automated adversary emulation to test security controls effectiveness",
		Icon:        "Swords",
		Category:    "validation", DisplayOrder: 31, Release: ReleaseStatusBeta,
		UserFacing: true,
		Depends: []Dependency{
			{ModuleID: ModuleAttackerProfiles, Type: DependencyHard, Reason: "simulation requires an attacker profile to emulate"},
			{ModuleID: ModuleAssets, Type: DependencyHard, Reason: "simulation needs target assets"},
		},
		Routes: []string{"/api/v1/simulations"},
	},
	{
		ID: ModuleControlTesting, Slug: "control-testing", Name: "Control Testing",
		Description: "Validate security controls (firewalls, WAF, IDS/IPS) with automated test cases",
		Icon:        "ShieldCheck",
		Category:    "validation", DisplayOrder: 32, Release: ReleaseStatusBeta,
		UserFacing: true,
		Depends: []Dependency{
			{ModuleID: ModuleCompensatingControls, Type: DependencyHard, Reason: "control testing validates compensating controls"},
		},
		Routes: []string{"/api/v1/control-tests"},
		Jobs:   []string{"ControlTestSchedulerController"},
	},
	{
		ID: ModuleCompensatingControls, Slug: "compensating-controls", Name: "Compensating Controls",
		Description: "Controls that reduce finding severity (WAF, EDR, IPS, …)",
		Icon:        "ShieldCheck",
		Category:    "validation", DisplayOrder: 33, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "ctem:compensating_controls:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "compensating controls reduce severity of findings"},
		},
		Routes: []string{"/api/v1/compensating-controls"},
	},
	{
		ID: ModuleRemediation, Slug: "remediation", Name: "Remediation",
		Description: "Remediation campaigns that group the fixes for many findings",
		Icon:        "CheckSquare",
		Category:    "mobilization", DisplayOrder: 40, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "findings:remediation:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "remediation closes findings"},
		},
		Routes: []string{"/api/v1/remediation/campaigns"},
		Jobs:   []string{"RemediationProgressController"},
	},
	{
		ID: ModuleSuppressions, Slug: "suppressions", Name: "Suppressions",
		Description: "Finding suppression rules to mute known false positives",
		Icon:        "EyeOff",
		Category:    "mobilization", DisplayOrder: 41, Release: ReleaseStatusReleased,
		Permission: "findings:suppressions:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "suppressions suppress findings"},
		},
		Routes: []string{"/api/v1/suppressions"},
	},
	{
		ID: ModuleWorkflows, Slug: "workflows", Name: "Workflows",
		Description: "Trigger-action automation for finding lifecycle (assignment, notification, sync)",
		Icon:        "GitPullRequest",
		Category:    "mobilization", DisplayOrder: 43, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "findings:workflows:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencySoft, Reason: "finding-lifecycle triggers are a subset of workflow triggers"},
			{ModuleID: ModuleIntegrations, Type: DependencySoft, Reason: "most workflow actions route through integrations (Jira, Slack)"},
		},
		Routes: []string{"/api/v1/workflows", "/api/v1/workflow-runs"},
		Jobs:   []string{"AutomationRunReaper"},
	},
	{
		ID: ModuleReports, Slug: "reports", Name: "Reports",
		Description: "Security reports and analytics",
		Icon:        "FileText",
		Category:    "insights", DisplayOrder: 50, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "reports:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencySoft, Reason: "most report types render finding data"},
		},
		Routes: []string{"/api/v1/reports/schedules"},
		Jobs:   []string{"ReportScheduler"},
	},
	{
		ID: ModuleAudit, Slug: "audit", Name: "Audit",
		Description: "Audit log for tracking all actions",
		Icon:        "History",
		Category:    "insights", DisplayOrder: 51, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "audit:read",
		Jobs:       []string{"AuditChainVerifyController", "AuditRetentionController"},
	},
	{
		ID: ModuleCTEMMaturity, Slug: "ctem-maturity", Name: "CTEM Maturity",
		Description: "Per-tenant CTEM invariant health — F1-F4, B1-B7, O1-O3",
		Icon:        "ShieldCheck",
		Category:    "insights", DisplayOrder: 52, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "dashboard:read",
		Depends: []Dependency{
			{ModuleID: ModuleCTEMCycles, Type: DependencyHard, Reason: "maturity is computed across CTEM cycles"},
			{ModuleID: ModuleFindings, Type: DependencySoft, Reason: "F3/B4 invariants rely on finding SLA data"},
		},
	},
	{
		ID: ModuleExecutiveSummary, Slug: "executive-summary", Name: "Executive Summary",
		Description: "Board-ready PDF rollup of risk, breaches, SLAs",
		Icon:        "FileText",
		Category:    "insights", DisplayOrder: 53, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "reports:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencyHard, Reason: "exec summary rolls up finding metrics"},
			{ModuleID: ModuleScans, Type: DependencySoft, Reason: "scan coverage metrics appear on the summary"},
		},
	},
	{
		ID: ModuleMITRECoverage, Slug: "mitre-coverage", Name: "MITRE Coverage",
		Description: "MITRE ATT&CK technique coverage across detections + controls",
		Icon:        "Shield",
		Category:    "insights", DisplayOrder: 54, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "threat_intel:read",
		Depends: []Dependency{
			{ModuleID: ModuleThreatIntel, Type: DependencyHard, Reason: "coverage maps detections to MITRE techniques"},
			{ModuleID: ModuleCompensatingControls, Type: DependencySoft, Reason: "control coverage appears on the heatmap"},
		},
	},
	{
		ID: ModuleSBOMExport, Slug: "sbom-export", Name: "SBOM Export",
		Description: "Export Software Bill of Materials in CycloneDX / SPDX",
		Icon:        "Download",
		Category:    "insights", DisplayOrder: 55, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "assets:components:read",
		Depends: []Dependency{
			{ModuleID: ModuleComponents, Type: DependencyHard, Reason: "SBOM is generated from the component inventory"},
		},
	},
	{
		ID: ModuleIntegrations, Slug: "integrations", Name: "Integrations",
		Description: "Integrations (SCM, Notifications, CI/CD, Ticketing, SIEM)",
		Icon:        "Plug",
		Category:    "settings", DisplayOrder: 60, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "integrations:read",
		Jobs:       []string{"SCMSyncController", "DefectDojoSyncController", "TenableSCSyncController"},
	},
	{
		ID: ModuleIntegrationsSCM, Slug: "scm", Name: "SCM Integrations",
		Description: "Source code management integrations",
		Icon:        "GitBranch",
		Category:    "settings", DisplayOrder: 1, Release: ReleaseStatusReleased,
		Parent: ModuleIntegrations,
	},
	{
		ID: ModuleIntegrationsNotifications, Slug: "notifications", Name: "Notification Channels",
		Description: "Notification channel integrations",
		Icon:        "Bell",
		Category:    "settings", DisplayOrder: 2, Release: ReleaseStatusReleased,
		Core:   true,
		Parent: ModuleIntegrations,
	},
	{
		ID: ModuleIntegrationsTicketing, Slug: "ticketing", Name: "Ticketing",
		Description: "Issue tracking integrations",
		Icon:        "Ticket",
		Category:    "settings", DisplayOrder: 3, Release: ReleaseStatusReleased,
		Parent: ModuleIntegrations,
	},
	{
		ID: ModuleIntegrationsCloud, Slug: "cloud", Name: "Cloud Providers",
		Description: "Cloud provider integrations",
		Icon:        "Cloud",
		Category:    "settings", DisplayOrder: 4, Release: ReleaseStatusReleased,
		Parent: ModuleIntegrations,
	},
	{
		ID: ModuleIntegrationsSIEM, Slug: "siem", Name: "SIEM",
		Description: "SIEM integrations",
		Icon:        "Shield",
		Category:    "settings", DisplayOrder: 5, Release: ReleaseStatusReleased,
		Parent: ModuleIntegrations,
	},
	{
		ID: ModuleIntegrationsScanners, Slug: "scanners", Name: "Scanners",
		Description: "External scanner integrations",
		Icon:        "Search",
		Category:    "settings", DisplayOrder: 6, Release: ReleaseStatusReleased,
		Parent: ModuleIntegrations,
	},
	{
		ID: ModuleIntegrationsAPI, Slug: "api_int", Name: "API Integrations",
		Description: "API integrations",
		Icon:        "Zap",
		Category:    "settings", DisplayOrder: 8, Release: ReleaseStatusReleased,
		Parent: ModuleIntegrations,
	},
	{
		ID: ModuleIntegrationsPipelines, Slug: "pipelines_int", Name: "Pipeline Integrations",
		Description: "CI/CD pipeline integrations",
		Icon:        "GitPullRequest",
		Category:    "settings", DisplayOrder: 9, Release: ReleaseStatusReleased,
		Parent: ModuleIntegrations,
	},
	{
		ID: ModuleSensors, Slug: "sensors", Name: "Sensors",
		Description: "Sensors: scanners, agents and collectors that report to the platform",
		Icon:        "Cpu",
		Category:    "settings", DisplayOrder: 61, Release: ReleaseStatusReleased,
		Core:       true,
		Permission: "sensors:read",
		Jobs:       []string{"SensorHealthController", "SensorEventRetentionController", "HeartbeatHistoryRetentionController"},
	},
	{
		ID: ModuleTeam, Slug: "team", Name: "Team",
		Description: "Team members management and invitations",
		Icon:        "Users",
		Category:    "settings", DisplayOrder: 62, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "team:read",
		Jobs:       []string{"MemberAccessExpiryController", "TeamMembershipExpiryController", "AccessRequestRetentionController", "RoleSyncController", "IdleWorkspaceController"},
	},
	{
		ID: ModuleGroups, Slug: "groups", Name: "Groups",
		Description: "Data scope groups (Teams) for access control",
		Icon:        "UsersCog",
		Category:    "settings", DisplayOrder: 63, Release: ReleaseStatusReleased,
		Core:       true,
		Permission: "team:groups:read",
		Jobs:       []string{"ScopeReconciliationController"},
	},
	{
		ID: ModuleRoles, Slug: "roles", Name: "Roles",
		Description: "Custom RBAC roles and permission management",
		Icon:        "Shield",
		Category:    "settings", DisplayOrder: 64, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "team:roles:read",
	},
	{
		ID: ModuleSettings, Slug: "settings", Name: "Settings",
		Description: "General workspace settings, Risk Scoring, and Module configuration",
		Icon:        "Settings",
		Category:    "settings", DisplayOrder: 65, Release: ReleaseStatusReleased,
		Core:       true,
		UserFacing: true,
		Permission: "settings:read",
	},
	{
		ID: ModuleAPIKeys, Slug: "api_keys", Name: "API Keys",
		Description: "API key management for programmatic access",
		Icon:        "Key",
		Category:    "settings", DisplayOrder: 66, Release: ReleaseStatusReleased,
		Core:       true,
		Permission: "integrations:api_keys:read",
	},
	{
		ID: ModuleNotificationSettings, Slug: "notification_settings", Name: "Notifications",
		Description: "Notification channel settings and delivery configuration",
		Icon:        "Bell",
		Category:    "settings", DisplayOrder: 68, Release: ReleaseStatusReleased,
		Core:       true,
		Permission: "integrations:notifications:read",
	},
	{
		ID: ModuleTools, Slug: "tools", Name: "Tools",
		Description: "Security tools and capabilities management",
		Icon:        "Wrench",
		Category:    "operations", DisplayOrder: 81, Release: ReleaseStatusReleased,
		Permission: "scans:tools:read",
	},
	{
		ID: ModuleScanProfiles, Slug: "scan_profiles", Name: "Scan Profiles",
		Description: "Scan configuration profiles",
		Icon:        "Sliders",
		Category:    "operations", DisplayOrder: 83, Release: ReleaseStatusReleased,
		Permission: "scans:profiles:read",
		Depends: []Dependency{
			{ModuleID: ModuleScans, Type: DependencyHard, Reason: "profiles are parameterised scan configurations"},
		},
	},
	{
		ID: ModuleIOCs, Slug: "iocs", Name: "IOCs",
		Description: "Indicators of Compromise",
		Icon:        "Fingerprint",
		Category:    "operations", DisplayOrder: 84, Release: ReleaseStatusReleased,
		Permission: "threat_intel:read",
		Depends: []Dependency{
			{ModuleID: ModuleThreatIntel, Type: DependencySoft, Reason: "IOC enrichment pulls from threat intel feeds"},
		},
		Routes: []string{"/api/v1/iocs"},
	},
	{
		ID: ModuleCompliance, Slug: "compliance", Name: "Compliance",
		Description: "Compliance frameworks, controls and audit-readiness mappings",
		Icon:        "ClipboardCheck",
		Category:    "compliance", DisplayOrder: 90, Release: ReleaseStatusReleased,
		UserFacing: true,
		Permission: "compliance:frameworks:read",
		Depends: []Dependency{
			{ModuleID: ModuleFindings, Type: DependencySoft, Reason: "compliance reports aggregate findings against frameworks"},
		},
		Routes: []string{"/api/v1/compliance"},
		MCP:    []string{"compliance_posture"},
	},
}
