// Package openapischema compares the request and response shapes (the
// definitions) of two OpenAPI 2.0 documents generated by swag.
//
// The spec is generated, not committed, so a pull request's contract change is
// visible only by generating the base branch's spec and the head's and
// comparing them: tools/openapidiff does that in Web CI and reports the result
// on the pull request.
//
// Only the shape is compared, which is stable across environments: the
// definition names and, per definition, its required list and each property's
// name, type, $ref, items type/$ref and enum. Descriptions, examples and format
// keywords are ignored (swag is not byte-reproducible across environments: a
// clean runner drops `format: int64` on some map fields a developer machine
// emits).
package openapischema

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type schema struct {
	Type                 any                `yaml:"type"`
	Ref                  string             `yaml:"$ref"`
	Enum                 []any              `yaml:"enum"`
	Required             []string           `yaml:"required"`
	Items                *schema            `yaml:"items"`
	Properties           map[string]*schema `yaml:"properties"`
	AdditionalProperties any                `yaml:"additionalProperties"`
	AllOf                []*schema          `yaml:"allOf"`
}

// Definitions are the named schemas of one spec.
type Definitions map[string]*schema

type spec struct {
	Definitions Definitions `yaml:"definitions"`
}

// Load reads the definitions of a swagger 2.0 file.
func Load(path string) (Definitions, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return Parse(raw)
}

// Parse reads the definitions of a swagger 2.0 document.
func Parse(raw []byte) (Definitions, error) {
	var s spec
	if err := yaml.Unmarshal(raw, &s); err != nil {
		return nil, err
	}
	return s.Definitions, nil
}

// shape renders a schema's structure on one line, ignoring descriptions,
// examples and format.
func shape(s *schema) string {
	if s == nil {
		return "-"
	}
	var b strings.Builder
	if s.Ref != "" {
		b.WriteString("ref=" + s.Ref)
	}
	if s.Type != nil {
		fmt.Fprintf(&b, " type=%v", s.Type)
	}
	if len(s.Enum) > 0 {
		vals := make([]string, len(s.Enum))
		for i, v := range s.Enum {
			vals[i] = fmt.Sprint(v)
		}
		sort.Strings(vals)
		b.WriteString(" enum=" + strings.Join(vals, ","))
	}
	if s.Items != nil {
		b.WriteString(" items=(" + shape(s.Items) + ")")
	}
	if s.AdditionalProperties != nil {
		if m, ok := s.AdditionalProperties.(map[string]any); ok {
			if r, ok := m["$ref"].(string); ok {
				b.WriteString(" additional=ref=" + r)
			} else if t, ok := m["type"]; ok {
				fmt.Fprintf(&b, " additional=type=%v", t)
			} else {
				b.WriteString(" additional")
			}
		} else {
			fmt.Fprintf(&b, " additional=%v", s.AdditionalProperties)
		}
	}
	for _, a := range s.AllOf {
		b.WriteString(" allOf=(" + shape(a) + ")")
	}
	return strings.TrimSpace(b.String())
}

// topShape is a definition's own shape, without its properties.
func topShape(d *schema) string {
	return shape(&schema{Type: d.Type, Ref: d.Ref, Enum: d.Enum, Items: d.Items, AdditionalProperties: d.AdditionalProperties, AllOf: d.AllOf})
}

// Change kinds. Breaking ones can break an existing client.
const (
	DefinitionRemoved = "definition removed"
	DefinitionAdded   = "definition added"
	DefinitionChanged = "definition shape changed"
	PropertyRemoved   = "property removed"
	PropertyAdded     = "property added"
	PropertyChanged   = "property shape changed"
	RequiredAdded     = "now required"
	RequiredRemoved   = "no longer required"
)

// Change is one difference between the definitions of two specs.
type Change struct {
	Kind       string
	Definition string
	Property   string
	Before     string
	After      string
}

// Breaking reports whether the change can break an existing client: something
// it reads or sends disappeared, changed shape, or became required.
func (c Change) Breaking() bool {
	switch c.Kind {
	case DefinitionRemoved, DefinitionChanged, PropertyRemoved, PropertyChanged, RequiredAdded:
		return true
	}
	return false
}

// Compare lists the shape differences from base to head, sorted by
// definition, then property, then kind.
func Compare(base, head Definitions) []Change {
	var out []Change
	for name, b := range base {
		h, ok := head[name]
		if !ok {
			out = append(out, Change{Kind: DefinitionRemoved, Definition: name})
			continue
		}
		out = append(out, compareDefinition(name, b, h)...)
	}
	for name := range head {
		if _, ok := base[name]; !ok {
			out = append(out, Change{Kind: DefinitionAdded, Definition: name})
		}
	}
	sort.Slice(out, func(i, j int) bool {
		a, b := out[i], out[j]
		if a.Definition != b.Definition {
			return a.Definition < b.Definition
		}
		if a.Property != b.Property {
			return a.Property < b.Property
		}
		return a.Kind < b.Kind
	})
	return out
}

func compareDefinition(name string, b, h *schema) []Change {
	if b == nil {
		b = &schema{}
	}
	if h == nil {
		h = &schema{}
	}
	var out []Change
	if bs, hs := topShape(b), topShape(h); bs != hs {
		out = append(out, Change{Kind: DefinitionChanged, Definition: name, Before: bs, After: hs})
	}
	for p, bp := range b.Properties {
		hp, ok := h.Properties[p]
		switch {
		case !ok:
			out = append(out, Change{Kind: PropertyRemoved, Definition: name, Property: p, Before: shape(bp)})
		case shape(bp) != shape(hp):
			out = append(out, Change{Kind: PropertyChanged, Definition: name, Property: p, Before: shape(bp), After: shape(hp)})
		}
	}
	for p, hp := range h.Properties {
		if _, ok := b.Properties[p]; !ok {
			out = append(out, Change{Kind: PropertyAdded, Definition: name, Property: p, After: shape(hp)})
		}
	}
	breq, hreq := set(b.Required), set(h.Required)
	for p := range hreq {
		if !breq[p] {
			out = append(out, Change{Kind: RequiredAdded, Definition: name, Property: p})
		}
	}
	for p := range breq {
		if !hreq[p] {
			out = append(out, Change{Kind: RequiredRemoved, Definition: name, Property: p})
		}
	}
	return out
}

func set(xs []string) map[string]bool {
	m := make(map[string]bool, len(xs))
	for _, x := range xs {
		m[x] = true
	}
	return m
}
