package openapischema

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestCommittedSpecMatchesFreshGeneration runs when OPENAPI_FRESH_SPEC names a
// spec just generated by `make swagger` into a temporary directory
// (scripts/check-openapi.sh does that); otherwise it is skipped.
func TestCommittedSpecMatchesFreshGeneration(t *testing.T) {
	fresh := os.Getenv("OPENAPI_FRESH_SPEC")
	if fresh == "" {
		t.Skip("OPENAPI_FRESH_SPEC not set; run scripts/check-openapi.sh")
	}
	committed, err := Load(filepath.Join("..", "..", "..", "api", "openapi", "swagger.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	generated, err := Load(fresh)
	if err != nil {
		t.Fatal(err)
	}
	missing, extra := Diff(Flatten(generated), Flatten(committed))
	if len(missing) > 0 || len(extra) > 0 {
		t.Fatalf("api/openapi/swagger.yaml does not describe the Go types: run `make swagger` (then `make api-types` at the root) and commit both.\n"+
			"  in the annotations, not in the committed spec:\n    %s\n  in the committed spec, not in the annotations:\n    %s",
			strings.Join(missing, "\n    "), strings.Join(extra, "\n    "))
	}
}

func TestFlattenIgnoresCosmetics(t *testing.T) {
	a := map[string]*schema{"T": {Type: "object", Properties: map[string]*schema{
		"n": {Type: "integer"}, "s": {Type: "array", Items: &schema{Type: "string"}},
	}}}
	b := map[string]*schema{"T": {Type: "object", Properties: map[string]*schema{
		"s": {Type: "array", Items: &schema{Type: "string"}}, "n": {Type: "integer"},
	}}}
	if m, e := Diff(Flatten(a), Flatten(b)); len(m)+len(e) != 0 {
		t.Fatalf("order must not matter: %v %v", m, e)
	}
}

func TestFlattenCatchesShapeDrift(t *testing.T) {
	committed := map[string]*schema{"T": {Type: "object", Properties: map[string]*schema{"a": {Type: "string"}}}}
	for name, gen := range map[string]map[string]*schema{
		"new field":    {"T": {Type: "object", Properties: map[string]*schema{"a": {Type: "string"}, "b": {Type: "string"}}}},
		"type changed": {"T": {Type: "object", Properties: map[string]*schema{"a": {Type: "integer"}}}},
		"new required": {"T": {Type: "object", Required: []string{"a"}, Properties: map[string]*schema{"a": {Type: "string"}}}},
		"new def":      {"T": committed["T"], "U": {Type: "object"}},
		"enum changed": {"T": {Type: "object", Properties: map[string]*schema{"a": {Type: "string", Enum: []any{"x"}}}}},
	} {
		if m, _ := Diff(Flatten(gen), Flatten(committed)); len(m) == 0 {
			t.Errorf("%s: drift not detected", name)
		}
	}
}

func TestLoadParsesTheCommittedSpec(t *testing.T) {
	defs, err := Load(filepath.Join("..", "..", "..", "api", "openapi", "swagger.yaml"))
	if err != nil || len(defs) == 0 {
		t.Fatalf("defs=%d err=%v", len(defs), err)
	}
}
