#!/usr/bin/env python3
"""Generate the RFC index table in api/docs/rfcs/README.md from the RFC headers.

Every RFC file is api/docs/rfcs/RFC-NNN-<slug>.md (or RFC-NNN.N-<slug>.md) and
starts with an H1 "# RFC-NNN: Title" (or "# RFC-NNN — Title"). Its header (the
lines before the first "## " heading) carries a Status field in one of the
forms the RFCs use:

    - **Status**: Accepted ...        > Status: **Accepted** ...
    **Status:** Accepted ...          | Status | Accepted ... |

Companion documents (appendices, reviews, phase details) share the number but
their H1 does not read "RFC-NNN: Title"; they are linked from their RFC, not
indexed. Each RFC number must have exactly one primary document.

The table between the BEGIN/END markers in the README is rewritten; everything
else in the README is hand-written and kept.

    python3 scripts/rfc_index.py          # rewrite the README
    python3 scripts/rfc_index.py --check  # exit 1 if the README is stale (CI)
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RFC_DIR = ROOT / "api" / "docs" / "rfcs"
README = RFC_DIR / "README.md"
BEGIN = "<!-- BEGIN RFC INDEX: generated by scripts/rfc_index.py, do not edit -->"
END = "<!-- END RFC INDEX -->"

FILE_RE = re.compile(r"^RFC-(\d{3}(?:\.\d+)?)-.+\.md$")
STATUS_RES = [
    # | Status | value |
    re.compile(r"^\|\s*\**Status\**\s*\|\s*(?P<v>.*?)\s*\|\s*$"),
    # - **Status**: v / > **Status:** v / > Status: v / Status: v
    re.compile(r"^(?:[-*]\s+|>\s*)?(?:\*\*Status\*\*\s*:|\*\*Status:\*\*|Status\s*:)\s*(?P<v>.*)$"),
]
# A new header field ("> Scope:", "- **Owner**:", "| Related |") ends a status.
FIELD_RE = re.compile(r"^(?:[-*]\s+|>\s*)?\**[A-Z][\w /()-]{0,30}\**\s*:|^\||^#")
MAX_STATUS = 220


class IndexError_(Exception):
    pass


def first_sentence(text: str) -> str:
    """Cut text after its first sentence, ignoring dots inside () [] or `code`."""
    depth, code = 0, False
    for i, ch in enumerate(text):
        if ch == "`":
            code = not code
        elif code:
            continue
        elif ch in "([":
            depth += 1
        elif ch in ")]":
            depth = max(0, depth - 1)
        elif ch == "." and depth == 0 and (i + 1 == len(text) or text[i + 1] == " "):
            return text[: i + 1]
    return text


def shorten(text: str) -> str:
    text = first_sentence(text).strip()
    if len(text) > MAX_STATUS:
        # Long status lines are "Status — detail": keep the status.
        for sep in (" — ", "; "):
            head = text.split(sep, 1)[0]
            if (
                len(head) < len(text)
                and head.count("`") % 2 == 0
                and head.count("**") % 2 == 0
                and head.count("(") == head.count(")")
            ):
                text = head
                break
    return text


def status_of(lines: list[str], name: str) -> str:
    for i, line in enumerate(lines):
        for rx in STATUS_RES:
            m = rx.match(line)
            if not m:
                continue
            parts = [m.group("v").strip()]
            if rx is not STATUS_RES[0]:
                quoted = line.lstrip().startswith(">")
                for nxt in lines[i + 1 :]:
                    body = nxt.strip()
                    if quoted:
                        if not body.startswith(">"):
                            break
                        body = body[1:].strip()
                    if not body or FIELD_RE.match(nxt.strip()) or body.startswith(("- ", "* ")):
                        break
                    parts.append(body)
            value = " ".join(p for p in parts if p)
            if value:
                return shorten(value)
    raise IndexError_(f"{name}: no Status field in the header (before the first '## ' heading)")


def collect() -> list[tuple[str, str, str, str]]:
    rows: dict[str, tuple[str, str, str, str]] = {}
    numbers: set[str] = set()
    for path in sorted(RFC_DIR.glob("RFC-*.md")):
        m = FILE_RE.match(path.name)
        if not m:
            continue
        num = m.group(1)
        numbers.add(num.split(".")[0])
        lines = path.read_text(encoding="utf-8").splitlines()
        h1 = lines[0] if lines else ""
        t = re.match(rf"^# RFC-{re.escape(num)}\s*(?::|—|–|-)\s+(.+)$", h1)
        if not t:
            continue  # companion document
        if num in rows:
            raise IndexError_(f"RFC-{num}: two primary documents ({rows[num][1]}, {path.name})")
        header = []
        for line in lines[1:]:
            if line.startswith("## "):
                break
            header.append(line)
        title = t.group(1).strip()
        rows[num] = (num, path.name, title, status_of(header, path.name))
    missing = sorted(n for n in numbers if n not in rows)
    if missing:
        raise IndexError_(
            "no primary document for "
            + ", ".join(f"RFC-{n}" for n in missing)
            + ": its H1 must read '# RFC-NNN: Title' and match the file name"
        )

    def key(n: str) -> tuple[int, ...]:
        return tuple(int(p) for p in n.split("."))

    return [rows[n] for n in sorted(rows, key=key)]


def cell(text: str) -> str:
    return re.sub(r"(?<!\\)\|", r"\\|", text)


def table(rows: list[tuple[str, str, str, str]]) -> str:
    out = ["| RFC | Title | Status |", "|-----|-------|--------|"]
    for num, name, title, status in rows:
        out.append(f"| [RFC-{num}]({name}) | {cell(title)} | {cell(status)} |")
    return "\n".join(out)


def render(readme: str, rows) -> str:
    start, end = readme.find(BEGIN), readme.find(END)
    if start < 0 or end < start:
        raise IndexError_(f"{README.relative_to(ROOT)}: missing the {BEGIN!r} / {END!r} markers")
    return readme[: start + len(BEGIN)] + "\n" + table(rows) + "\n" + readme[end:]


def main(argv: list[str]) -> int:
    check = "--check" in argv
    try:
        current = README.read_text(encoding="utf-8")
        wanted = render(current, collect())
    except IndexError_ as e:
        print(f"rfc_index: {e}", file=sys.stderr)
        return 1
    if check:
        if wanted != current:
            print(
                "rfc_index: api/docs/rfcs/README.md is stale. Run `python3 scripts/rfc_index.py` "
                "and commit the result (edit the RFC's own H1/Status, not the table).",
                file=sys.stderr,
            )
            return 1
        print("rfc_index: README up to date")
        return 0
    if wanted != current:
        README.write_text(wanted, encoding="utf-8")
        print("rfc_index: README rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
