/**
 * Code generated by api/cmd/gen-asset-types. DO NOT EDIT.
 *
 * Source of truth: api/configs/asset-types.yaml (RFC-042 §6.3).
 * Run `make generate-asset-types` in api/ to regenerate.
 *
 * The full registry (attributes, facets, columns, sections, relationships)
 * is served by GET /api/v1/asset-types; this file carries the closed sets
 * and labels for compile-time checks and for rendering before it loads.
 */

export const ASSET_REGISTRY_VERSION = '51bcaac255568151'

export type AssetLens =
  | 'external_surface'
  | 'applications'
  | 'cloud_infra'
  | 'containers_k8s'
  | 'code'
  | 'identities'
  | 'data'
  | 'network'

export type AssetClass =
  | 'domain'
  | 'ip_address'
  | 'certificate'
  | 'service'
  | 'web_endpoint'
  | 'application'
  | 'host'
  | 'function'
  | 'cloud_account'
  | 'container'
  | 'cluster'
  | 'artifact_registry'
  | 'code_repo'
  | 'identity'
  | 'data_store'
  | 'network'
  | 'other'

export type RegistryAssetType =
  | 'domain'
  | 'subdomain'
  | 'ip_address'
  | 'certificate'
  | 'service'
  | 'http_service'
  | 'open_port'
  | 'discovered_url'
  | 'application'
  | 'website'
  | 'api'
  | 'mobile_app'
  | 'host'
  | 'compute'
  | 'endpoint'
  | 'serverless'
  | 'cloud_account'
  | 'container'
  | 'kubernetes'
  | 'kubernetes_cluster'
  | 'kubernetes_namespace'
  | 'container_registry'
  | 'repository'
  | 'identity'
  | 'iam_user'
  | 'iam_role'
  | 'service_account'
  | 'database'
  | 'data_store'
  | 'storage'
  | 's3_bucket'
  | 'network'
  | 'vpc'
  | 'subnet'
  | 'firewall'
  | 'load_balancer'
  | 'unclassified'

export type LegacyAssetCategory =
  | 'external_surface'
  | 'application'
  | 'infrastructure'
  | 'network'
  | 'cloud'
  | 'data'
  | 'code'
  | 'identity'
  | 'other'

export const ASSET_LENSES: ReadonlyArray<{
  id: AssetLens
  label: string
  classes: readonly AssetClass[]
}> = [
  {
    id: 'external_surface',
    label: 'External surface',
    classes: ['domain', 'ip_address', 'certificate', 'service', 'web_endpoint'],
  },
  {
    id: 'applications',
    label: 'Applications',
    classes: ['application'],
  },
  {
    id: 'cloud_infra',
    label: 'Cloud & infrastructure',
    classes: ['host', 'function', 'cloud_account'],
  },
  {
    id: 'containers_k8s',
    label: 'Containers & Kubernetes',
    classes: ['container', 'cluster', 'artifact_registry'],
  },
  {
    id: 'code',
    label: 'Code',
    classes: ['code_repo'],
  },
  {
    id: 'identities',
    label: 'Identities',
    classes: ['identity'],
  },
  {
    id: 'data',
    label: 'Data',
    classes: ['data_store'],
  },
  {
    id: 'network',
    label: 'Network',
    classes: ['network'],
  },
]

export const ASSET_CLASSES: ReadonlyArray<{
  id: AssetClass
  label: string
  lens: AssetLens | null
}> = [
  { id: 'domain', label: 'Domain', lens: 'external_surface' },
  { id: 'ip_address', label: 'IP address', lens: 'external_surface' },
  { id: 'certificate', label: 'Certificate', lens: 'external_surface' },
  { id: 'service', label: 'Service', lens: 'external_surface' },
  { id: 'web_endpoint', label: 'Web endpoint', lens: 'external_surface' },
  { id: 'application', label: 'Application', lens: 'applications' },
  { id: 'host', label: 'Host', lens: 'cloud_infra' },
  { id: 'function', label: 'Function', lens: 'cloud_infra' },
  { id: 'cloud_account', label: 'Cloud account', lens: 'cloud_infra' },
  { id: 'container', label: 'Container', lens: 'containers_k8s' },
  { id: 'cluster', label: 'Cluster', lens: 'containers_k8s' },
  { id: 'artifact_registry', label: 'Artifact registry', lens: 'containers_k8s' },
  { id: 'code_repo', label: 'Code repository', lens: 'code' },
  { id: 'identity', label: 'Identity', lens: 'identities' },
  { id: 'data_store', label: 'Data store', lens: 'data' },
  { id: 'network', label: 'Network', lens: 'network' },
  { id: 'other', label: 'Other', lens: null },
]

/** The class of each type. Stored aliases keep their own class: see ASSET_ALIAS_CLASSES. */
export const ASSET_TYPE_CLASSES: Readonly<Record<RegistryAssetType, AssetClass>> = {
  domain: 'domain',
  subdomain: 'domain',
  ip_address: 'ip_address',
  certificate: 'certificate',
  service: 'service',
  http_service: 'service',
  open_port: 'service',
  discovered_url: 'web_endpoint',
  application: 'application',
  website: 'application',
  api: 'application',
  mobile_app: 'application',
  host: 'host',
  compute: 'host',
  endpoint: 'host',
  serverless: 'function',
  cloud_account: 'cloud_account',
  container: 'container',
  kubernetes: 'cluster',
  kubernetes_cluster: 'cluster',
  kubernetes_namespace: 'cluster',
  container_registry: 'artifact_registry',
  repository: 'code_repo',
  identity: 'identity',
  iam_user: 'identity',
  iam_role: 'identity',
  service_account: 'identity',
  database: 'data_store',
  data_store: 'data_store',
  storage: 'data_store',
  s3_bucket: 'data_store',
  network: 'network',
  vpc: 'network',
  subnet: 'network',
  firewall: 'network',
  load_balancer: 'network',
  unclassified: 'other',
}

/**
 * Stored (type, sub_type) pairs whose class differs from the type's class,
 * keyed `type/sub_type`: a host with sub_type serverless is a function.
 */
export const ASSET_ALIAS_CLASSES: Readonly<Record<string, AssetClass>> = {
  'service/discovered_url': 'web_endpoint',
  'host/serverless': 'function',
  'storage/container_registry': 'artifact_registry',
}

export const LEGACY_ASSET_CATEGORY_LABELS: Readonly<Record<LegacyAssetCategory, string>> = {
  external_surface: 'External Surface',
  application: 'Applications',
  infrastructure: 'Infrastructure',
  network: 'Network',
  cloud: 'Cloud',
  data: 'Data',
  code: 'Code',
  identity: 'Identity',
  other: 'Other',
}

/** The core types: the only values an asset's `type` holds (RFC-042 §6.3.8). */
export type StoredAssetType =
  | 'domain'
  | 'subdomain'
  | 'ip_address'
  | 'certificate'
  | 'service'
  | 'application'
  | 'host'
  | 'cloud_account'
  | 'container'
  | 'kubernetes'
  | 'repository'
  | 'identity'
  | 'database'
  | 'storage'
  | 'network'
  | 'unclassified'

export const STORED_ASSET_TYPES: readonly StoredAssetType[] = [
  'domain',
  'subdomain',
  'ip_address',
  'certificate',
  'service',
  'application',
  'host',
  'cloud_account',
  'container',
  'kubernetes',
  'repository',
  'identity',
  'database',
  'storage',
  'network',
  'unclassified',
]

/** The closed sub-type list of each core type (a sub-type is a kind). */
export const ASSET_SUB_TYPES: Readonly<Record<StoredAssetType, readonly string[]>> = {
  domain: [],
  subdomain: [],
  ip_address: [],
  certificate: [],
  service: ['http', 'open_port', 'discovered_url'],
  application: ['website', 'api', 'mobile_app'],
  host: ['compute', 'serverless', 'workstation'],
  cloud_account: ['account', 'project', 'subscription', 'organization'],
  container: ['image'],
  kubernetes: ['cluster', 'namespace', 'workload'],
  repository: [],
  identity: ['iam_user', 'iam_role', 'service_account', 'identity_provider'],
  database: ['relational', 'document', 'key_value', 'graph', 'warehouse', 'vector'],
  storage: ['bucket', 'file_share', 'disk', 'container_registry'],
  network: [
    'vpc',
    'subnet',
    'ip_block',
    'vlan',
    'security_group',
    'firewall',
    'router',
    'switch',
    'load_balancer',
    'vpn_gateway',
    'wireless_controller',
    'access_point',
    'ids_ips',
  ],
  unclassified: [],
}

/**
 * Every non-core name the relationship constraints use (aliases and virtual
 * names), resolved to the stored (core type, sub-type). A core type name
 * stands for itself with any sub-type.
 */
export const ASSET_RELATIONSHIP_NAMES: Readonly<
  Record<string, { type: StoredAssetType; subType?: string }>
> = {
  http_service: { type: 'service', subType: 'http' },
  open_port: { type: 'service', subType: 'open_port' },
  discovered_url: { type: 'service', subType: 'discovered_url' },
  website: { type: 'application', subType: 'website' },
  api: { type: 'application', subType: 'api' },
  mobile_app: { type: 'application', subType: 'mobile_app' },
  compute: { type: 'host', subType: 'compute' },
  endpoint: { type: 'host', subType: 'workstation' },
  serverless: { type: 'host', subType: 'serverless' },
  kubernetes_cluster: { type: 'kubernetes', subType: 'cluster' },
  kubernetes_namespace: { type: 'kubernetes', subType: 'namespace' },
  container_registry: { type: 'storage', subType: 'container_registry' },
  iam_user: { type: 'identity', subType: 'iam_user' },
  iam_role: { type: 'identity', subType: 'iam_role' },
  service_account: { type: 'identity', subType: 'service_account' },
  data_store: { type: 'database' },
  s3_bucket: { type: 'storage', subType: 'bucket' },
  vpc: { type: 'network', subType: 'vpc' },
  subnet: { type: 'network', subType: 'subnet' },
  firewall: { type: 'network', subType: 'firewall' },
  load_balancer: { type: 'network', subType: 'load_balancer' },
  k8s_cluster: { type: 'kubernetes', subType: 'cluster' },
  k8s_workload: { type: 'kubernetes', subType: 'workload' },
  container_image: { type: 'container', subType: 'image' },
  api_collection: { type: 'application', subType: 'api' },
  api_endpoint: { type: 'service', subType: 'discovered_url' },
  identity_provider: { type: 'identity', subType: 'identity_provider' },
  mobile: { type: 'application', subType: 'mobile_app' },
}

/** Input-only alias names and the (core type, sub-type) they are stored as. */
export const ASSET_TYPE_ALIASES: Readonly<
  Record<string, { type: StoredAssetType; subType?: string }>
> = {
  http_service: { type: 'service', subType: 'http' },
  open_port: { type: 'service', subType: 'open_port' },
  discovered_url: { type: 'service', subType: 'discovered_url' },
  website: { type: 'application', subType: 'website' },
  api: { type: 'application', subType: 'api' },
  mobile_app: { type: 'application', subType: 'mobile_app' },
  compute: { type: 'host', subType: 'compute' },
  endpoint: { type: 'host', subType: 'workstation' },
  serverless: { type: 'host', subType: 'serverless' },
  kubernetes_cluster: { type: 'kubernetes', subType: 'cluster' },
  kubernetes_namespace: { type: 'kubernetes', subType: 'namespace' },
  container_registry: { type: 'storage', subType: 'container_registry' },
  iam_user: { type: 'identity', subType: 'iam_user' },
  iam_role: { type: 'identity', subType: 'iam_role' },
  service_account: { type: 'identity', subType: 'service_account' },
  data_store: { type: 'database' },
  s3_bucket: { type: 'storage', subType: 'bucket' },
  vpc: { type: 'network', subType: 'vpc' },
  subnet: { type: 'network', subType: 'subnet' },
  firewall: { type: 'network', subType: 'firewall' },
  load_balancer: { type: 'network', subType: 'load_balancer' },
  web_application: { type: 'application', subType: 'website' },
}

export type AssetPropertyFormat = 'ip' | 'url' | 'code'

export interface AssetPropertyDefinition {
  label: string
  labelVi: string
  format?: AssetPropertyFormat
  synonyms?: readonly string[]
  classes?: readonly AssetClass[]
}

/** Every property key of the schema, with its labels and display format. */
export const ASSET_PROPERTIES: Readonly<Record<string, AssetPropertyDefinition>> = {
  account_id: { label: 'Account ID', labelVi: 'ID tài khoản', format: 'code' },
  account_name: { label: 'Account name', labelVi: 'Tên tài khoản' },
  aliases: { label: 'Former names', labelVi: 'Tên cũ' },
  api_server_url: { label: 'API server', labelVi: 'Máy chủ API', format: 'url' },
  api_type: { label: 'API type', labelVi: 'Loại API' },
  architecture: { label: 'Architecture', labelVi: 'Kiến trúc' },
  archived: { label: 'Archived', labelVi: 'Đã lưu trữ' },
  arn: { label: 'ARN', labelVi: 'ARN', format: 'code' },
  asn: { label: 'ASN', labelVi: 'ASN' },
  asn_org: { label: 'ASN organization', labelVi: 'Tổ chức ASN' },
  auth_required: { label: 'Authentication required', labelVi: 'Yêu cầu xác thực' },
  authentication: { label: 'Authentication', labelVi: 'Xác thực' },
  availability_zone: { label: 'Availability zone', labelVi: 'Vùng khả dụng' },
  backup_retention_days: {
    label: 'Backup retention (days)',
    labelVi: 'Lưu bản sao lưu (ngày)',
  },
  banner: { label: 'Banner', labelVi: 'Banner', format: 'code', classes: ['service'] },
  base_url: { label: 'Base URL', labelVi: 'URL gốc', format: 'url' },
  bucket_name: { label: 'Bucket', labelVi: 'Bucket' },
  business_impact_notes: {
    label: 'Business impact notes',
    labelVi: 'Ghi chú tác động nghiệp vụ',
  },
  business_impact_score: {
    label: 'Business impact score',
    labelVi: 'Điểm tác động nghiệp vụ',
  },
  canonical_url: { label: 'Repository URL', labelVi: 'URL kho mã', format: 'url' },
  cdn: { label: 'CDN', labelVi: 'CDN' },
  certificate: { label: 'Certificate details', labelVi: 'Chi tiết chứng chỉ' },
  cidr: { label: 'CIDR', labelVi: 'CIDR' },
  cidr_block: { label: 'CIDR block', labelVi: 'Dải CIDR' },
  city: { label: 'City', labelVi: 'Thành phố' },
  cluster_name: { label: 'Cluster', labelVi: 'Cụm' },
  cms: { label: 'CMS', labelVi: 'CMS' },
  cname_target: { label: 'CNAME target', labelVi: 'Đích CNAME' },
  container_id: { label: 'Container ID', labelVi: 'ID container', format: 'code' },
  content_length: {
    label: 'Content length',
    labelVi: 'Độ dài nội dung',
    classes: ['service', 'web_endpoint', 'application'],
  },
  content_type: {
    label: 'Content type',
    labelVi: 'Kiểu nội dung',
    classes: ['service', 'web_endpoint', 'application'],
  },
  cors_enabled: { label: 'CORS enabled', labelVi: 'Bật CORS' },
  country: { label: 'Country', labelVi: 'Quốc gia' },
  cpe: { label: 'CPE', labelVi: 'CPE', format: 'code' },
  cpu_count: { label: 'CPUs', labelVi: 'Số CPU' },
  created_at: { label: 'Created', labelVi: 'Ngày tạo' },
  default_branch: { label: 'Default branch', labelVi: 'Nhánh mặc định' },
  depth: { label: 'Crawl depth', labelVi: 'Độ sâu thu thập' },
  device_type: { label: 'Device type', labelVi: 'Loại thiết bị' },
  dhcp_enabled: { label: 'DHCP enabled', labelVi: 'Bật DHCP' },
  direction: { label: 'Direction', labelVi: 'Chiều' },
  discovery_source: { label: 'Discovery source', labelVi: 'Nguồn phát hiện' },
  discovery_tool: { label: 'Discovery tool', labelVi: 'Công cụ phát hiện' },
  display_name: { label: 'Display name', labelVi: 'Tên hiển thị' },
  dns_name: { label: 'DNS name', labelVi: 'Tên DNS' },
  dns_record_types: { label: 'DNS record types', labelVi: 'Loại bản ghi DNS' },
  dns_records: { label: 'DNS records', labelVi: 'Bản ghi DNS' },
  dns_servers: { label: 'DNS servers', labelVi: 'Máy chủ DNS', format: 'ip' },
  documentation_url: { label: 'Documentation', labelVi: 'Tài liệu', format: 'url' },
  domain: { label: 'Domain details', labelVi: 'Chi tiết tên miền' },
  domain_level: { label: 'Domain level', labelVi: 'Cấp tên miền' },
  edr_installed: { label: 'EDR installed', labelVi: 'Đã cài EDR' },
  email: { label: 'Email', labelVi: 'Email' },
  encrypted: { label: 'Encrypted', labelVi: 'Đã mã hóa' },
  encryption_enabled: { label: 'Encryption enabled', labelVi: 'Bật mã hóa' },
  encryption_type: { label: 'Encryption type', labelVi: 'Kiểu mã hóa' },
  endpoint: { label: 'Endpoint', labelVi: 'Endpoint' },
  endpoints_count: { label: 'Endpoints', labelVi: 'Số endpoint' },
  engine: { label: 'Engine', labelVi: 'Engine' },
  expires_at: { label: 'Expires', labelVi: 'Ngày hết hạn' },
  fingerprint_sha256: {
    label: 'SHA-256 fingerprint',
    labelVi: 'Dấu vân tay SHA-256',
    format: 'code',
  },
  firewall_id: { label: 'Firewall ID', labelVi: 'ID tường lửa', format: 'code' },
  flow_logs_enabled: { label: 'Flow logs enabled', labelVi: 'Bật flow log' },
  forms: { label: 'Forms', labelVi: 'Biểu mẫu' },
  fqdn: { label: 'FQDN', labelVi: 'FQDN' },
  framework: { label: 'Framework', labelVi: 'Framework' },
  function_name: { label: 'Function name', labelVi: 'Tên hàm' },
  gateway: { label: 'Gateway', labelVi: 'Cổng mạng (gateway)', format: 'ip' },
  geolocation: { label: 'Geolocation', labelVi: 'Vị trí địa lý' },
  groups: { label: 'Groups', labelVi: 'Nhóm' },
  handler: { label: 'Handler', labelVi: 'Handler', format: 'code' },
  has_waf: { label: 'Behind a WAF', labelVi: 'Có WAF' },
  host: { label: 'Host', labelVi: 'Máy chủ' },
  hostname: { label: 'Hostname', labelVi: 'Tên máy' },
  hypervisor: { label: 'Hypervisor', labelVi: 'Hypervisor' },
  identity_hints: { label: 'Identity hints', labelVi: 'Gợi ý định danh' },
  image: { label: 'Image', labelVi: 'Image' },
  image_count: { label: 'Images', labelVi: 'Số image' },
  image_id: { label: 'Image ID', labelVi: 'ID image', format: 'code' },
  immutable_tags: { label: 'Immutable tags', labelVi: 'Tag bất biến' },
  instance_id: { label: 'Instance ID', labelVi: 'ID máy ảo', format: 'code' },
  instance_type: { label: 'Instance type', labelVi: 'Loại máy ảo' },
  ip_address: { label: 'IP details', labelVi: 'Chi tiết địa chỉ IP' },
  ip_addresses: {
    label: 'IP addresses',
    labelVi: 'Địa chỉ IP',
    format: 'ip',
    synonyms: ['ip', 'ips', 'ip_address', 'resolved_ip', 'resolved_ips', 'addresses'],
  },
  is_default: { label: 'Default', labelVi: 'Mặc định' },
  is_expired: { label: 'Expired', labelVi: 'Đã hết hạn' },
  is_private: { label: 'Private address', labelVi: 'Địa chỉ nội bộ' },
  is_public: { label: 'Public', labelVi: 'Công khai' },
  is_reserved: { label: 'Reserved address', labelVi: 'Địa chỉ dành riêng' },
  is_self_signed: { label: 'Self-signed', labelVi: 'Tự ký' },
  is_virtual: { label: 'Virtual machine', labelVi: 'Máy ảo' },
  is_wildcard: { label: 'Wildcard', labelVi: 'Wildcard' },
  isp: { label: 'ISP', labelVi: 'Nhà cung cấp mạng' },
  issuer_cn: { label: 'Issuer CN', labelVi: 'CN bên cấp' },
  issuer_org: { label: 'Issuer organization', labelVi: 'Tổ chức cấp' },
  kernel_version: { label: 'Kernel version', labelVi: 'Phiên bản kernel' },
  key_algorithm: { label: 'Key algorithm', labelVi: 'Thuật toán khóa' },
  key_size: { label: 'Key size', labelVi: 'Độ dài khóa' },
  language: { label: 'Language', labelVi: 'Ngôn ngữ' },
  last_commit_at: { label: 'Last commit', labelVi: 'Commit gần nhất' },
  last_login: { label: 'Last sign-in', labelVi: 'Đăng nhập lần cuối' },
  last_modified: { label: 'Last modified', labelVi: 'Sửa đổi lần cuối' },
  last_used: { label: 'Last used', labelVi: 'Dùng lần cuối' },
  lb_type: { label: 'Load balancer type', labelVi: 'Loại cân bằng tải' },
  listeners: { label: 'Listeners', labelVi: 'Listener' },
  logging_enabled: { label: 'Logging enabled', labelVi: 'Bật ghi log' },
  mac_addresses: { label: 'MAC addresses', labelVi: 'Địa chỉ MAC', format: 'code' },
  max_session_duration: {
    label: 'Max session duration (s)',
    labelVi: 'Thời lượng phiên tối đa (giây)',
  },
  memory_gb: { label: 'Memory (GB)', labelVi: 'Bộ nhớ (GB)' },
  memory_mb: { label: 'Memory (MB)', labelVi: 'Bộ nhớ (MB)' },
  method: { label: 'Method', labelVi: 'Phương thức' },
  mfa_enabled: { label: 'MFA enabled', labelVi: 'Bật MFA' },
  min_sdk_version: { label: 'Minimum SDK', labelVi: 'SDK tối thiểu' },
  nameservers: {
    label: 'Name servers',
    labelVi: 'Máy chủ tên miền',
    synonyms: ['nameserver'],
  },
  namespace: { label: 'Namespace', labelVi: 'Namespace' },
  namespace_count: { label: 'Namespaces', labelVi: 'Số namespace' },
  namespace_labels: { label: 'Namespace labels', labelVi: 'Nhãn namespace' },
  network_plugin: { label: 'Network plugin', labelVi: 'Plugin mạng' },
  network_policies: { label: 'Network policies', labelVi: 'Chính sách mạng' },
  networks: { label: 'Networks', labelVi: 'Mạng' },
  node_count: { label: 'Nodes', labelVi: 'Số node' },
  not_after: { label: 'Valid until', labelVi: 'Hiệu lực đến' },
  not_before: { label: 'Valid from', labelVi: 'Hiệu lực từ' },
  organization_id: { label: 'Organization ID', labelVi: 'ID tổ chức', format: 'code' },
  os_family: { label: 'OS family', labelVi: 'Họ hệ điều hành' },
  os_name: { label: 'Operating system', labelVi: 'Hệ điều hành' },
  os_version: { label: 'OS version', labelVi: 'Phiên bản hệ điều hành' },
  package_name: { label: 'Package name', labelVi: 'Tên gói', format: 'code' },
  parameters: { label: 'Parameters', labelVi: 'Tham số' },
  parent_domain: { label: 'Parent domain', labelVi: 'Tên miền cha' },
  permissions: { label: 'Permissions', labelVi: 'Quyền' },
  platform: { label: 'Platform', labelVi: 'Nền tảng' },
  pod_count: { label: 'Pods', labelVi: 'Số pod' },
  pod_security_enabled: { label: 'Pod security enabled', labelVi: 'Bật bảo mật pod' },
  policies: { label: 'Policies', labelVi: 'Chính sách' },
  port: {
    label: 'Port',
    labelVi: 'Cổng',
    classes: ['service', 'data_store', 'application', 'web_endpoint'],
  },
  ports: { label: 'Ports', labelVi: 'Các cổng' },
  principal_id: { label: 'Principal ID', labelVi: 'ID principal', format: 'code' },
  private_ip: { label: 'Private IP', labelVi: 'IP nội bộ', format: 'ip' },
  privileged: { label: 'Privileged', labelVi: 'Đặc quyền' },
  product: { label: 'Product', labelVi: 'Sản phẩm' },
  protocol: { label: 'Protocol', labelVi: 'Giao thức' },
  provider: { label: 'Provider', labelVi: 'Nhà cung cấp' },
  public_access: { label: 'Public access', labelVi: 'Truy cập công khai' },
  public_ip: { label: 'Public IP', labelVi: 'IP công khai', format: 'ip' },
  publicly_accessible: { label: 'Publicly accessible', labelVi: 'Truy cập công khai' },
  rate_limiting: { label: 'Rate limiting', labelVi: 'Giới hạn tần suất' },
  rbac_enabled: { label: 'RBAC enabled', labelVi: 'Bật RBAC' },
  redirect_url: { label: 'Redirects to', labelVi: 'Chuyển hướng tới', format: 'url' },
  region: { label: 'Region', labelVi: 'Vùng' },
  registered_at: { label: 'Registered', labelVi: 'Ngày đăng ký' },
  registrar: { label: 'Registrar', labelVi: 'Nhà đăng ký' },
  registry_url: { label: 'Registry URL', labelVi: 'URL registry', format: 'url' },
  repository_count: { label: 'Repositories', labelVi: 'Số kho' },
  response_code: { label: 'Response code', labelVi: 'Mã phản hồi' },
  response_time_ms: {
    label: 'Response time (ms)',
    labelVi: 'Thời gian phản hồi (ms)',
    classes: ['service', 'web_endpoint', 'application'],
  },
  role: { label: 'Role', labelVi: 'Vai trò' },
  role_id: { label: 'Role ID', labelVi: 'ID vai trò', format: 'code' },
  role_name: { label: 'Role name', labelVi: 'Tên vai trò' },
  roles: { label: 'Roles', labelVi: 'Vai trò' },
  root_domain: { label: 'Root domain', labelVi: 'Tên miền gốc' },
  rules: { label: 'Rules', labelVi: 'Quy tắc' },
  runtime: { label: 'Runtime', labelVi: 'Môi trường chạy' },
  sans: { label: 'Subject alternative names', labelVi: 'Tên thay thế (SAN)', synonyms: ['san'] },
  scan_on_push: { label: 'Scan on push', labelVi: 'Quét khi đẩy' },
  scheme: { label: 'Scheme', labelVi: 'Lược đồ' },
  secondary_cidrs: { label: 'Secondary CIDRs', labelVi: 'Dải CIDR phụ' },
  serial_number: { label: 'Serial number', labelVi: 'Số sê-ri', format: 'code' },
  server: { label: 'Server', labelVi: 'Máy chủ web' },
  service: { label: 'Service', labelVi: 'Dịch vụ' },
  service_count: { label: 'Services', labelVi: 'Số dịch vụ' },
  signature_algorithm: { label: 'Signature algorithm', labelVi: 'Thuật toán chữ ký' },
  source: { label: 'Source', labelVi: 'Nguồn' },
  ssl_enforced: { label: 'SSL enforced', labelVi: 'Bắt buộc SSL' },
  ssl_policy: { label: 'SSL policy', labelVi: 'Chính sách SSL' },
  state: { label: 'State', labelVi: 'Trạng thái' },
  status_code: {
    label: 'Status code',
    labelVi: 'Mã trạng thái',
    classes: ['service', 'web_endpoint', 'application'],
  },
  store_url: { label: 'Store page', labelVi: 'Trang cửa hàng', format: 'url' },
  subject_cn: { label: 'Subject CN', labelVi: 'CN chủ thể' },
  subnet_id: { label: 'Subnet ID', labelVi: 'ID subnet', format: 'code' },
  target_sdk_version: { label: 'Target SDK', labelVi: 'SDK mục tiêu' },
  technologies: { label: 'Technologies', labelVi: 'Công nghệ', synonyms: ['technology'] },
  timeout_seconds: { label: 'Timeout (s)', labelVi: 'Thời gian chờ (giây)' },
  title: { label: 'Title', labelVi: 'Tiêu đề' },
  tls_enabled: { label: 'TLS enabled', labelVi: 'Bật TLS' },
  tls_version: { label: 'TLS version', labelVi: 'Phiên bản TLS' },
  transport: { label: 'Transport', labelVi: 'Giao thức truyền tải' },
  trust_policy: { label: 'Trust policy', labelVi: 'Chính sách tin cậy' },
  url: { label: 'URL', labelVi: 'URL', format: 'url' },
  user: { label: 'User', labelVi: 'Người dùng' },
  user_id: { label: 'User ID', labelVi: 'ID người dùng', format: 'code' },
  username: { label: 'Username', labelVi: 'Tên đăng nhập' },
  uses_ssl_pinning: { label: 'SSL pinning', labelVi: 'Ghim SSL' },
  version: { label: 'Version', labelVi: 'Phiên bản' },
  versioning_enabled: { label: 'Versioning enabled', labelVi: 'Bật lập phiên bản' },
  visibility: { label: 'Visibility', labelVi: 'Chế độ hiển thị' },
  vlan_id: { label: 'VLAN ID', labelVi: 'ID VLAN' },
  vpc_id: { label: 'VPC ID', labelVi: 'ID VPC', format: 'code' },
  waf: { label: 'WAF', labelVi: 'WAF' },
  waf_vendor: { label: 'WAF vendor', labelVi: 'Nhà cung cấp WAF' },
  whois: { label: 'WHOIS', labelVi: 'WHOIS' },
  workload_kind: { label: 'Workload kind', labelVi: 'Loại workload' },
  x_native_sub_type: { label: 'Sensor sub-type', labelVi: 'Loại con từ cảm biến' },
  zone: { label: 'Zone', labelVi: 'Khu vực' },
}

/** The property keys every type may hold (platform keys, CTIS technical blocks). */
export const ASSET_COMMON_PROPERTIES: readonly string[] = [
  'discovery_source',
  'discovery_tool',
  'aliases',
  'identity_hints',
  'x_native_sub_type',
  'business_impact_score',
  'business_impact_notes',
  'domain',
  'ip_address',
  'service',
  'certificate',
]

/** The attribute keys of each type, in display order. */
export const ASSET_TYPE_PROPERTIES: Readonly<Record<RegistryAssetType, readonly string[]>> = {
  domain: [
    'root_domain',
    'domain_level',
    'parent_domain',
    'ip_addresses',
    'cname_target',
    'dns_record_types',
    'is_wildcard',
    'registrar',
    'registered_at',
    'expires_at',
    'nameservers',
    'dns_records',
    'whois',
  ],
  subdomain: [
    'parent_domain',
    'root_domain',
    'domain_level',
    'ip_addresses',
    'cname_target',
    'dns_record_types',
    'discovery_source',
    'is_wildcard',
  ],
  ip_address: [
    'version',
    'hostname',
    'asn',
    'asn_org',
    'isp',
    'country',
    'city',
    'geolocation',
    'ports',
    'is_private',
    'is_reserved',
  ],
  certificate: [
    'serial_number',
    'subject_cn',
    'sans',
    'issuer_cn',
    'issuer_org',
    'not_before',
    'not_after',
    'signature_algorithm',
    'key_algorithm',
    'key_size',
    'fingerprint_sha256',
    'is_self_signed',
    'is_expired',
    'is_wildcard',
  ],
  service: [
    'ip_addresses',
    'port',
    'protocol',
    'transport',
    'product',
    'version',
    'banner',
    'cpe',
    'state',
    'tls_enabled',
    'tls_version',
    'auth_required',
    'response_time_ms',
  ],
  http_service: [
    'ip_addresses',
    'url',
    'host',
    'port',
    'scheme',
    'status_code',
    'title',
    'content_length',
    'content_type',
    'server',
    'technologies',
    'cdn',
    'waf',
    'tls_version',
    'response_time_ms',
    'redirect_url',
  ],
  open_port: [
    'ip_addresses',
    'host',
    'port',
    'protocol',
    'state',
    'service',
    'version',
    'banner',
    'cpe',
    'discovery_tool',
  ],
  discovered_url: [
    'url',
    'method',
    'status_code',
    'content_type',
    'content_length',
    'source',
    'depth',
    'parameters',
    'forms',
  ],
  application: ['url', 'title', 'technologies', 'server', 'framework', 'authentication', 'has_waf'],
  website: [
    'ip_addresses',
    'url',
    'title',
    'technologies',
    'server',
    'cms',
    'framework',
    'response_code',
    'tls_version',
    'has_waf',
    'waf_vendor',
  ],
  api: [
    'ip_addresses',
    'base_url',
    'api_type',
    'version',
    'authentication',
    'documentation_url',
    'rate_limiting',
    'cors_enabled',
    'endpoints_count',
  ],
  mobile_app: [
    'platform',
    'package_name',
    'version',
    'store_url',
    'min_sdk_version',
    'target_sdk_version',
    'permissions',
    'uses_ssl_pinning',
  ],
  host: [
    'hostname',
    'fqdn',
    'os_family',
    'os_name',
    'os_version',
    'kernel_version',
    'architecture',
    'cpu_count',
    'memory_gb',
    'ip_addresses',
    'mac_addresses',
    'is_virtual',
    'hypervisor',
  ],
  compute: [
    'ip_addresses',
    'provider',
    'instance_id',
    'instance_type',
    'region',
    'zone',
    'private_ip',
    'public_ip',
    'vpc_id',
    'state',
    'image_id',
    'platform',
  ],
  endpoint: [
    'ip_addresses',
    'hostname',
    'os_family',
    'os_version',
    'device_type',
    'user',
    'edr_installed',
  ],
  serverless: [
    'provider',
    'function_name',
    'runtime',
    'handler',
    'memory_mb',
    'timeout_seconds',
    'region',
    'arn',
    'role',
    'last_modified',
  ],
  cloud_account: [
    'provider',
    'account_id',
    'account_name',
    'region',
    'organization_id',
    'mfa_enabled',
  ],
  container: [
    'container_id',
    'image',
    'image_id',
    'runtime',
    'state',
    'created_at',
    'ports',
    'networks',
  ],
  kubernetes: [
    'provider',
    'version',
    'region',
    'cluster_name',
    'namespace',
    'workload_kind',
    'node_count',
    'rbac_enabled',
  ],
  kubernetes_cluster: [
    'cluster_name',
    'provider',
    'version',
    'region',
    'node_count',
    'namespace_count',
    'api_server_url',
    'network_plugin',
    'rbac_enabled',
    'pod_security_enabled',
    'network_policies',
  ],
  kubernetes_namespace: [
    'namespace',
    'cluster_name',
    'pod_count',
    'service_count',
    'namespace_labels',
  ],
  container_registry: [
    'provider',
    'registry_url',
    'repository_count',
    'image_count',
    'scan_on_push',
    'encryption_enabled',
    'immutable_tags',
  ],
  repository: [
    'provider',
    'visibility',
    'language',
    'default_branch',
    'canonical_url',
    'last_commit_at',
    'archived',
  ],
  identity: ['provider', 'principal_id', 'arn', 'email', 'mfa_enabled', 'privileged', 'last_used'],
  iam_user: [
    'provider',
    'user_id',
    'username',
    'arn',
    'email',
    'last_login',
    'mfa_enabled',
    'groups',
    'policies',
  ],
  iam_role: [
    'provider',
    'role_id',
    'role_name',
    'arn',
    'max_session_duration',
    'trust_policy',
    'policies',
    'last_used',
  ],
  service_account: ['provider', 'account_id', 'email', 'display_name', 'roles', 'namespace'],
  database: [
    'engine',
    'version',
    'provider',
    'endpoint',
    'port',
    'encrypted',
    'ssl_enforced',
    'publicly_accessible',
    'backup_retention_days',
  ],
  data_store: ['engine', 'provider', 'encrypted', 'publicly_accessible'],
  storage: [
    'provider',
    'bucket_name',
    'region',
    'arn',
    'versioning_enabled',
    'encryption_enabled',
    'encryption_type',
    'public_access',
    'logging_enabled',
  ],
  s3_bucket: [
    'bucket_name',
    'region',
    'arn',
    'versioning_enabled',
    'encryption_enabled',
    'public_access',
  ],
  network: ['cidr', 'gateway', 'dns_servers', 'dhcp_enabled', 'vlan_id', 'zone'],
  vpc: [
    'provider',
    'vpc_id',
    'cidr_block',
    'secondary_cidrs',
    'region',
    'is_default',
    'flow_logs_enabled',
  ],
  subnet: ['provider', 'subnet_id', 'vpc_id', 'cidr_block', 'availability_zone', 'is_public'],
  firewall: ['ip_addresses', 'provider', 'firewall_id', 'vpc_id', 'direction', 'rules'],
  load_balancer: [
    'ip_addresses',
    'provider',
    'lb_type',
    'dns_name',
    'scheme',
    'vpc_id',
    'listeners',
    'ssl_policy',
  ],
  unclassified: [],
}
