#!/usr/bin/env bash
#
# check-openapi.sh — the OpenAPI contract gate.
#
# WHY: api/openapi/swagger.yaml is generated by swag from the handler
# // @Router annotations. It is not committed: this script generates it, then
# checks it. Before the gate existed the spec drifted far enough to describe a
# different server:
#
#   • 30 documented paths had no handler and no route anywhere in the repo
#     (/admin/platform-agents, /plans, /tenants/{id}/subscription, ...),
#     leftovers from a closed-source era.
#   • 40 real endpoints were undocumented, the whole /notifications API among
#     them, plus GET /auth/providers.
#
# That is a client bug, not a docs bug. The web console generates its API types
# from this file, so a stale entry ships a request to an endpoint that does not
# exist, and a missing entry hides a feature from every client.
#
# THE CHECKS (tools/lint/openapicontract), on the freshly generated spec:
#
#   A. every @Router annotation is in the spec, and every spec path is an
#      annotation  (swag read every handler)
#   B. every documented path+method has a registered route  (no phantoms)
#   C. every registered route is documented or listed in
#      api/openapi/undocumented-routes.txt  (the debt is frozen, not growing)
#   D. a documented operation names its path parameters as the router does,
#      or is listed in api/openapi/param-name-drift.txt  (RFC-041; shrink-only)
#
# Set comparison is stable across swag's formatting quirks (swag is not
# byte-reproducible across environments) and is the thing a generated client
# actually depends on. What a pull request changes in the contract is shown by
# the Web CI contract job (tools/openapidiff, base vs head).
#
# Usage:
#   scripts/check-openapi.sh
#
# To fix a failure: follow the message.
#
# Exit codes: 0 = contract holds, 1 = drift, 2 = tooling error.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ ! -f "$REPO_ROOT/api/openapi/undocumented-routes.txt" ]; then
  echo "check-openapi: api/openapi/undocumented-routes.txt is missing." >&2
  echo "               Without the baseline the debt check cannot run, and a" >&2
  echo "               check that cannot run must not report as passed." >&2
  exit 2
fi

cd "$REPO_ROOT"

# Always generate: the gate checks what the source produces now, never a spec
# left over from an earlier run.
if ! make -s swagger >/dev/null; then
  echo "check-openapi: generating the spec failed (make swagger)" >&2
  exit 2
fi

if GOWORK=off go test ./tools/lint/openapicontract/... -count=1; then
  echo "check-openapi: annotations, spec and routes agree."
  exit 0
fi

cat >&2 <<'EOF'

────────────────────────────────────────────────────────────────────────────
OpenAPI contract check failed. The message above names the operations.

  • "in the spec with no @Router annotation" / "annotated but absent"
        swag did not read a handler (a parse error above, or a handler
        outside internal/infra/http/handler). Fix the annotation.

  • "have no registered route"
        The spec advertises an endpoint that 404s. Either register the route,
        or correct the handler's @Router to the path it is really served on.

  • "neither documented nor baselined"
        A new route no client can discover. Add a // @Router annotation — or,
        if documenting it now is genuinely out of scope, add the line to api/openapi/undocumented-routes.txt so the
        choice is visible in review.
────────────────────────────────────────────────────────────────────────────
EOF
exit 1
