#!/usr/bin/env bash
#
# check-openapi.sh — the OpenAPI contract gate.
#
# WHY: api/openapi/swagger.yaml is generated by swag from the handler
# // @Router annotations, and nothing ever verified that the committed file
# still matched them. It drifted far enough to describe a different server:
#
#   • 30 documented paths had no handler and no route anywhere in the repo
#     (/admin/platform-agents, /plans, /tenants/{id}/subscription, ...),
#     leftovers from a closed-source era.
#   • 40 real endpoints were undocumented, the whole /notifications API among
#     them, plus GET /auth/providers.
#
# That is a client bug, not a docs bug. The UI generates its API types from this
# file, so a stale entry ships a request to an endpoint that does not exist —
# which is exactly how the UI came to call GET /api/v1/me/event-types against a
# server that never had it — and a missing entry hides a feature from every
# client.
#
# WHY NOT "REGENERATE AND DIFF"
#
# The obvious gate is a byte comparison against a fresh regeneration. It was
# tried, on this branch, and it does not hold: swag is not hermetic across
# environments. A clean CI runner drops `format: int64` from some
# map[string]int64 fields that a developer machine emits, with the same pinned
# swag v1.16.4, the same Go 1.26.5 and a freshly downloaded module cache. Both
# documents say the same thing about the same Go types, so the gate would fail
# on a difference that describes no disagreement, that the developer who tripped
# it cannot fix, and whose only available resolution is to weaken or delete the
# gate. That is worse than no gate.
#
# So this gates the PROPERTY, not the byte representation — see
# tools/lint/openapicontract for the three set comparisons:
#
#   A. every @Router annotation is in the spec, and every spec path is an
#      annotation  (the spec is generated; you cannot hand-edit it)
#   B. every documented path+method has a registered route  (no phantoms)
#   C. every registered route is documented or listed in
#      api/openapi/undocumented-routes.txt  (the debt is frozen, not growing)
#   D. a documented operation names its path parameters as the router does,
#      or is listed in api/openapi/param-name-drift.txt  (RFC-041; shrink-only)
#   E. the committed definitions have the shape a fresh `make swagger` gives:
#      the same definitions, required lists, and per property the same name,
#      type, $ref, items and enum (tools/lint/openapischema). Descriptions,
#      examples and `format` are ignored, so swag's environment quirks cannot
#      fail it. Skip it locally with OPENAPI_SKIP_SCHEMA=1.
#
# Set comparison is stable across swag's formatting quirks and is the thing a
# generated client actually depends on.
#
# NOTE: the spec is generated-but-not-byte-gated. Cosmetic churn in swag's
# output — a format keyword, a description reflow — will not fail this check.
# What cannot drift is the set of operations.
#
# Usage:
#   scripts/check-openapi.sh
#
# To fix a failure: follow the message. Usually `make swagger` and commit.
#
# Exit codes: 0 = contract holds, 1 = drift, 2 = tooling error.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ ! -f "$REPO_ROOT/api/openapi/swagger.yaml" ]; then
  echo "check-openapi: api/openapi/swagger.yaml is missing." >&2
  exit 2
fi
if [ ! -f "$REPO_ROOT/api/openapi/undocumented-routes.txt" ]; then
  echo "check-openapi: api/openapi/undocumented-routes.txt is missing." >&2
  echo "               Without the baseline the debt check cannot run, and a" >&2
  echo "               check that cannot run must not report as passed." >&2
  exit 2
fi

cd "$REPO_ROOT"

schema_ok=1
if [ "${OPENAPI_SKIP_SCHEMA:-0}" != "1" ]; then
  SWAG_VERSION="${SWAG_VERSION:-v1.16.4}" # keep in step with the Makefile
  SWAG="$(command -v swag 2>/dev/null || echo "$(go env GOPATH)/bin/swag")"
  if ! "$SWAG" --version 2>/dev/null | grep -qF "$SWAG_VERSION"; then
    GOWORK=off GOFLAGS=-mod=mod go install "github.com/swaggo/swag/cmd/swag@$SWAG_VERSION" >&2 || {
      echo "check-openapi: cannot install swag $SWAG_VERSION" >&2; exit 2; }
    SWAG="$(go env GOPATH)/bin/swag"
  fi
  fresh="$(mktemp -d)"
  trap 'rm -rf "$fresh"' EXIT
  GOWORK=off go mod download
  if ! GOWORK=off "$SWAG" init --generalInfo cmd/server/main.go --output "$fresh" \
        --outputTypes yaml --parseDependency >"$fresh/swag.log" 2>&1; then
    echo "check-openapi: swag failed:" >&2
    tail -20 "$fresh/swag.log" >&2
    exit 2
  fi
  if ! OPENAPI_FRESH_SPEC="$fresh/swagger.yaml" GOWORK=off go test ./tools/lint/openapischema/... -count=1; then
    schema_ok=0
  fi
fi

if GOWORK=off go test ./tools/lint/openapicontract/... -count=1 && [ "$schema_ok" = 1 ]; then
  echo "check-openapi: annotations, spec and routes agree."
  exit 0
fi

cat >&2 <<'EOF'

────────────────────────────────────────────────────────────────────────────
OpenAPI contract check failed. The message above names the operations.

  • "in the committed spec with no @Router annotation"
        swagger.yaml is GENERATED. Run `make swagger` and commit the result.
        Never hand-edit it.

  • "annotated but absent from the committed spec"
        You changed a handler's @Router without regenerating.
        Run `make swagger` and commit the result.

  • "have no registered route"
        The spec advertises an endpoint that 404s. Either register the route,
        or correct the handler's @Router to the path it is really served on
        and rerun `make swagger`.

  • "does not describe the Go types"
        A request or response struct changed without regenerating.
        Run `make swagger`, then `make api-types` at the root, and commit both.

  • "neither documented nor baselined"
        A new route no client can discover. Add a // @Router annotation and
        run `make swagger` — or, if documenting it now is genuinely out of
        scope, add the line to api/openapi/undocumented-routes.txt so the
        choice is visible in review.
────────────────────────────────────────────────────────────────────────────
EOF
exit 1
